unit PopperJS;

interface

uses Interfaces, Classes;

type
  TPopperJS = class(TInterfacedObject,iModelJS)
    private
      FPack : TStringList;
      FCDN: boolean;
    public
      constructor Create;
      destructor Destroy; override;
      class function New : iModelJS;
      function PackJS : String;
      function CDN(Value : Boolean) : iModelJS;
      function Credenciais(Value : iModelCredenciais) : iModelJS;
      procedure PopperJS_1;
      procedure PopperJS_2;
      procedure PopperJS_3;
      procedure PopperJS_4;
      procedure PopperJS_5;
      procedure PopperJS_6;
  end;

implementation

uses
  SysUtils;

{ TPopperJS }

function TPopperJS.CDN(Value: Boolean): iModelJS;
begin
  Result := Self;
  FCDN := Value;
end;

constructor TPopperJS.Create;
begin
  FPack := TStringList.Create;
end;

function TPopperJS.Credenciais(Value: iModelCredenciais): iModelJS;
begin
  Result := Self;
end;

destructor TPopperJS.Destroy;
begin
  freeandnil(fpack);
  inherited;
end;

class function TPopperJS.New: iModelJS;
begin
  Result := Self.Create;
end;

procedure TPopperJS.PopperJS_1;
begin
  FPack.Add('<script>'+#13);
  FPack.Add('/**');
  FPack.Add(' * @popperjs/core v2.11.8 - MIT License');
  FPack.Add(' */');
  FPack.Add('');
  FPack.Add('(function (global, factory) {');
  FPack.Add('  typeof exports === ''object'' && typeof module !== ''undefined'' ? factory(exports) :');
  FPack.Add('  typeof define === ''function'' && define.amd ? define([''exports''], factory) :');
  FPack.Add('  (global = typeof globalThis !== ''undefined'' ? globalThis : global || self, factory(global.Popper = {}));');
  FPack.Add('}(this, (function (exports) { ''use strict'';');
  FPack.Add('');
  FPack.Add('  function getWindow(node) {');
  FPack.Add('    if (node == null) {');
  FPack.Add('      return window;');
  FPack.Add('    }');
  FPack.Add('');
  FPack.Add('    if (node.toString() !== ''[object Window]'') {');
  FPack.Add('      var ownerDocument = node.ownerDocument;');
  FPack.Add('      return ownerDocument ? ownerDocument.defaultView || window : window;');
  FPack.Add('    }');
  FPack.Add('');
  FPack.Add('    return node;');
  FPack.Add('  }');
  FPack.Add('');
  FPack.Add('  function isElement(node) {');
  FPack.Add('    var OwnElement = getWindow(node).Element;');
  FPack.Add('    return node instanceof OwnElement || node instanceof Element;');
  FPack.Add('  }');
  FPack.Add('');
  FPack.Add('  function isHTMLElement(node) {');
  FPack.Add('    var OwnElement = getWindow(node).HTMLElement;');
  FPack.Add('    return node instanceof OwnElement || node instanceof HTMLElement;');
  FPack.Add('  }');
  FPack.Add('');
  FPack.Add('  function isShadowRoot(node) {');
  FPack.Add('    // IE 11 has no ShadowRoot');
  FPack.Add('    if (typeof ShadowRoot === ''undefined'') {');
  FPack.Add('      return false;');
  FPack.Add('    }');
  FPack.Add('');
  FPack.Add('    var OwnElement = getWindow(node).ShadowRoot;');
  FPack.Add('    return node instanceof OwnElement || node instanceof ShadowRoot;');
  FPack.Add('  }');
  FPack.Add('');
  FPack.Add('  var max = Math.max;');
  FPack.Add('  var min = Math.min;');
  FPack.Add('  var round = Math.round;');
  FPack.Add('');
  FPack.Add('  function getUAString() {');
  FPack.Add('    var uaData = navigator.userAgentData;');
  FPack.Add('');
  FPack.Add('    if (uaData != null && uaData.brands && Array.isArray(uaData.brands)) {');
  FPack.Add('      return uaData.brands.map(function (item) {');
  FPack.Add('        return item.brand + "/" + item.version;');
  FPack.Add('      }).join('' '');');
  FPack.Add('    }');
  FPack.Add('');
  FPack.Add('    return navigator.userAgent;');
  FPack.Add('  }');
  FPack.Add('');
  FPack.Add('  function isLayoutViewport() {');
  FPack.Add('    return !/^((?!chrome|android).)*safari/i.test(getUAString());');
  FPack.Add('  }');
  FPack.Add('');
  FPack.Add('  function getBoundingClientRect(element, includeScale, isFixedStrategy) {');
  FPack.Add('    if (includeScale === void 0) {');
  FPack.Add('      includeScale = false;');
  FPack.Add('    }');
  FPack.Add('');
  FPack.Add('    if (isFixedStrategy === void 0) {');
  FPack.Add('      isFixedStrategy = false;');
  FPack.Add('    }');
  FPack.Add('');
  FPack.Add('    var clientRect = element.getBoundingClientRect();');
  FPack.Add('    var scaleX = 1;');
  FPack.Add('    var scaleY = 1;');
  FPack.Add('');
  FPack.Add('    if (includeScale && isHTMLElement(element)) {');
  FPack.Add('      scaleX = element.offsetWidth > 0 ? round(clientRect.width) / element.offsetWidth || 1 : 1;');
  FPack.Add('      scaleY = element.offsetHeight > 0 ? round(clientRect.height) / element.offsetHeight || 1 : 1;');
  FPack.Add('    }');
  FPack.Add('');
  FPack.Add('    var _ref = isElement(element) ? getWindow(element) : window,');
  FPack.Add('        visualViewport = _ref.visualViewport;');
  FPack.Add('');
  FPack.Add('    var addVisualOffsets = !isLayoutViewport() && isFixedStrategy;');
  FPack.Add('    var x = (clientRect.left + (addVisualOffsets && visualViewport ? visualViewport.offsetLeft : 0)) / scaleX;');
  FPack.Add('    var y = (clientRect.top + (addVisualOffsets && visualViewport ? visualViewport.offsetTop : 0)) / scaleY;');
  FPack.Add('    var width = clientRect.width / scaleX;');
  FPack.Add('    var height = clientRect.height / scaleY;');
  FPack.Add('    return {');
  FPack.Add('      width: width,');
  FPack.Add('      height: height,');
  FPack.Add('      top: y,');
  FPack.Add('      right: x + width,');
  FPack.Add('      bottom: y + height,');
  FPack.Add('      left: x,');
  FPack.Add('      x: x,');
  FPack.Add('      y: y');
  FPack.Add('    };');
  FPack.Add('  }');
  FPack.Add('');
  FPack.Add('  function getWindowScroll(node) {');
  FPack.Add('    var win = getWindow(node);');
  FPack.Add('    var scrollLeft = win.pageXOffset;');
  FPack.Add('    var scrollTop = win.pageYOffset;');
  FPack.Add('    return {');
  FPack.Add('      scrollLeft: scrollLeft,');
  FPack.Add('      scrollTop: scrollTop');
  FPack.Add('    };');
  FPack.Add('  }');
  FPack.Add('');
  FPack.Add('  function getHTMLElementScroll(element) {');
  FPack.Add('    return {');
  FPack.Add('      scrollLeft: element.scrollLeft,');
  FPack.Add('      scrollTop: element.scrollTop');
  FPack.Add('    };');
  FPack.Add('  }');
  FPack.Add('');
  FPack.Add('  function getNodeScroll(node) {');
  FPack.Add('    if (node === getWindow(node) || !isHTMLElement(node)) {');
  FPack.Add('      return getWindowScroll(node);');
  FPack.Add('    } else {');
  FPack.Add('      return getHTMLElementScroll(node);');
  FPack.Add('    }');
  FPack.Add('  }');
  FPack.Add('');
  FPack.Add('  function getNodeName(element) {');
  FPack.Add('    return element ? (element.nodeName || '''').toLowerCase() : null;');
  FPack.Add('  }');
  FPack.Add('');
  FPack.Add('  function getDocumentElement(element) {');
  FPack.Add('    // $FlowFixMe[incompatible-return]: assume body is always available');
  FPack.Add('    return ((isElement(element) ? element.ownerDocument : // $FlowFixMe[prop-missing]');
  FPack.Add('    element.document) || window.document).documentElement;');
  FPack.Add('  }');
  FPack.Add('');
  FPack.Add('  function getWindowScrollBarX(element) {');
  FPack.Add('    // If <html> has a CSS width greater than the viewport, then this will be');
  FPack.Add('    // incorrect for RTL.');
  FPack.Add('    // Popper 1 is broken in this case and never had a bug report so let''s assume');
  FPack.Add('    // it''s not an issue. I don''t think anyone ever specifies width on <html>');
  FPack.Add('    // anyway.');
  FPack.Add('    // Browsers where the left scrollbar doesn''t cause an issue report `0` for');
  FPack.Add('    // this (e.g. Edge 2019, IE11, Safari)');
  FPack.Add('    return getBoundingClientRect(getDocumentElement(element)).left + getWindowScroll(element).scrollLeft;');
  FPack.Add('  }');
  FPack.Add('');
  FPack.Add('  function getComputedStyle(element) {');
  FPack.Add('    return getWindow(element).getComputedStyle(element);');
  FPack.Add('  }');
  FPack.Add('');
  FPack.Add('  function isScrollParent(element) {');
  FPack.Add('    // Firefox wants us to check `-x` and `-y` variations as well');
  FPack.Add('    var _getComputedStyle = getComputedStyle(element),');
  FPack.Add('        overflow = _getComputedStyle.overflow,');
  FPack.Add('        overflowX = _getComputedStyle.overflowX,');
  FPack.Add('        overflowY = _getComputedStyle.overflowY;');
  FPack.Add('');
  FPack.Add('    return /auto|scroll|overlay|hidden/.test(overflow + overflowY + overflowX);');
  FPack.Add('  }');
  FPack.Add('');
  FPack.Add('  function isElementScaled(element) {');
  FPack.Add('    var rect = element.getBoundingClientRect();');
  FPack.Add('    var scaleX = round(rect.width) / element.offsetWidth || 1;');
  FPack.Add('    var scaleY = round(rect.height) / element.offsetHeight || 1;');
  FPack.Add('    return scaleX !== 1 || scaleY !== 1;');
  FPack.Add('  } // Returns the composite rect of an element relative to its offsetParent.');
  FPack.Add('  // Composite means it takes into account transforms as well as layout.');
  FPack.Add('');
  FPack.Add('');
  FPack.Add('  function getCompositeRect(elementOrVirtualElement, offsetParent, isFixed) {');
  FPack.Add('    if (isFixed === void 0) {');
  FPack.Add('      isFixed = false;');
  FPack.Add('    }');
  FPack.Add('');
  FPack.Add('    var isOffsetParentAnElement = isHTMLElement(offsetParent);');
  FPack.Add('    var offsetParentIsScaled = isHTMLElement(offsetParent) && isElementScaled(offsetParent);');
  FPack.Add('    var documentElement = getDocumentElement(offsetParent);');
  FPack.Add('    var rect = getBoundingClientRect(elementOrVirtualElement, offsetParentIsScaled, isFixed);');
  FPack.Add('    var scroll = {');
  FPack.Add('      scrollLeft: 0,');
  FPack.Add('      scrollTop: 0');
  FPack.Add('    };');
  FPack.Add('    var offsets = {');
  FPack.Add('      x: 0,');
  FPack.Add('      y: 0');
  FPack.Add('    };');
  FPack.Add('');
  FPack.Add('    if (isOffsetParentAnElement || !isOffsetParentAnElement && !isFixed) {');
  FPack.Add('      if (getNodeName(offsetParent) !== ''body'' || // https://github.com/popperjs/popper-core/issues/1078');
  FPack.Add('      isScrollParent(documentElement)) {');
  FPack.Add('        scroll = getNodeScroll(offsetParent);');
  FPack.Add('      }');
  FPack.Add('');
  FPack.Add('      if (isHTMLElement(offsetParent)) {');
  FPack.Add('        offsets = getBoundingClientRect(offsetParent, true);');
  FPack.Add('        offsets.x += offsetParent.clientLeft;');
  FPack.Add('        offsets.y += offsetParent.clientTop;');
  FPack.Add('      } else if (documentElement) {');
  FPack.Add('        offsets.x = getWindowScrollBarX(documentElement);');
  FPack.Add('      }');
  FPack.Add('    }');
  FPack.Add('');
  FPack.Add('    return {');
  FPack.Add('      x: rect.left + scroll.scrollLeft - offsets.x,');
  FPack.Add('      y: rect.top + scroll.scrollTop - offsets.y,');
  FPack.Add('      width: rect.width,');
  FPack.Add('      height: rect.height');
  FPack.Add('    };');
  FPack.Add('  }');
  FPack.Add('');
  FPack.Add('  // means it doesn''t take into account transforms.');
  FPack.Add('');
  FPack.Add('  function getLayoutRect(element) {');
  FPack.Add('    var clientRect = getBoundingClientRect(element); // Use the clientRect sizes if it''s not been transformed.');
  FPack.Add('    // Fixes https://github.com/popperjs/popper-core/issues/1223');
  FPack.Add('');
  FPack.Add('    var width = element.offsetWidth;');
  FPack.Add('    var height = element.offsetHeight;');
  FPack.Add('');
  FPack.Add('    if (Math.abs(clientRect.width - width) <= 1) {');
  FPack.Add('      width = clientRect.width;');
  FPack.Add('    }');
  FPack.Add('');
  FPack.Add('    if (Math.abs(clientRect.height - height) <= 1) {');
  FPack.Add('      height = clientRect.height;');
  FPack.Add('    }');
  FPack.Add('');
  FPack.Add('    return {');
  FPack.Add('      x: element.offsetLeft,');
  FPack.Add('      y: element.offsetTop,');
  FPack.Add('      width: width,');
  FPack.Add('      height: height');
  FPack.Add('    };');
  FPack.Add('  }');
  FPack.Add('');
  FPack.Add('  function getParentNode(element) {');
  FPack.Add('    if (getNodeName(element) === ''html'') {');
  FPack.Add('      return element;');
  FPack.Add('    }');
  FPack.Add('');
  FPack.Add('    return (// this is a quicker (but less type safe) way to save quite some bytes from the bundle');
  FPack.Add('      // $FlowFixMe[incompatible-return]');
  FPack.Add('      // $FlowFixMe[prop-missing]');
  FPack.Add('      element.assignedSlot || // step into the shadow DOM of the parent of a slotted node');
  FPack.Add('      element.parentNode || ( // DOM Element detected');
  FPack.Add('      isShadowRoot(element) ? element.host : null) || // ShadowRoot detected');
  FPack.Add('      // $FlowFixMe[incompatible-call]: HTMLElement is a Node');
  FPack.Add('      getDocumentElement(element) // fallback');
  FPack.Add('');
  FPack.Add('    );');
  FPack.Add('  }');
  FPack.Add('');
  FPack.Add('  function getScrollParent(node) {');
  FPack.Add('    if ([''html'', ''body'', ''#document''].indexOf(getNodeName(node)) >= 0) {');
  FPack.Add('      // $FlowFixMe[incompatible-return]: assume body is always available');
  FPack.Add('      return node.ownerDocument.body;');
  FPack.Add('    }');
  FPack.Add('');
  FPack.Add('    if (isHTMLElement(node) && isScrollParent(node)) {');
  FPack.Add('      return node;');
  FPack.Add('    }');
  FPack.Add('');
  FPack.Add('    return getScrollParent(getParentNode(node));');
  FPack.Add('  }');
  FPack.Add('');
  FPack.Add('  /*');
  FPack.Add('  given a DOM element, return the list of all scroll parents, up the list of ancesors');
  FPack.Add('  until we get to the top window object. This list is what we attach scroll listeners');
  FPack.Add('  to, because if any of these parent elements scroll, we''ll need to re-calculate the');
  FPack.Add('  reference element''s position.');
  FPack.Add('  */');
  FPack.Add('');
  FPack.Add('  function listScrollParents(element, list) {');
  FPack.Add('    var _element$ownerDocumen;');
  FPack.Add('');
  FPack.Add('    if (list === void 0) {');
  FPack.Add('      list = [];');
  FPack.Add('    }');
  FPack.Add('');
  FPack.Add('    var scrollParent = getScrollParent(element);');
  FPack.Add('    var isBody = scrollParent === ((_element$ownerDocumen = element.ownerDocument) == null ? void 0 : _element$ownerDocumen.body);');
  FPack.Add('    var win = getWindow(scrollParent);');
  FPack.Add('    var target = isBody ? [win].concat(win.visualViewport || [], isScrollParent(scrollParent) ? scrollParent : []) : scrollParent;');
  FPack.Add('    var updatedList = list.concat(target);');
  FPack.Add('    return isBody ? updatedList : // $FlowFixMe[incompatible-call]: isBody tells us target will be an HTMLElement here');
  FPack.Add('    updatedList.concat(listScrollParents(getParentNode(target)));');
  FPack.Add('  }');
  FPack.Add('');
  FPack.Add('  function isTableElement(element) {');
  FPack.Add('    return [''table'', ''td'', ''th''].indexOf(getNodeName(element)) >= 0;');
  FPack.Add('  }');
  FPack.Add('');
  FPack.Add('  function getTrueOffsetParent(element) {');
  FPack.Add('    if (!isHTMLElement(element) || // https://github.com/popperjs/popper-core/issues/837');
  FPack.Add('    getComputedStyle(element).position === ''fixed'') {');
  FPack.Add('      return null;');
  FPack.Add('    }');
  FPack.Add('');
  FPack.Add('    return element.offsetParent;');
  FPack.Add('  } // `.offsetParent` reports `null` for fixed elements, while absolute elements');
  FPack.Add('  // return the containing block');
  FPack.Add('');
  FPack.Add('');
  FPack.Add('  function getContainingBlock(element) {');
  FPack.Add('    var isFirefox = /firefox/i.test(getUAString());');
  FPack.Add('    var isIE = /Trident/i.test(getUAString());');
  FPack.Add('');
  FPack.Add('    if (isIE && isHTMLElement(element)) {');
  FPack.Add('      // In IE 9, 10 and 11 fixed elements containing block is always established by the viewport');
  FPack.Add('      var elementCss = getComputedStyle(element);');
  FPack.Add('');
  FPack.Add('      if (elementCss.position === ''fixed'') {');
  FPack.Add('        return null;');
  FPack.Add('      }');
  FPack.Add('    }');
  FPack.Add('');
  FPack.Add('    var currentNode = getParentNode(element);');
  FPack.Add('');
  FPack.Add('    if (isShadowRoot(currentNode)) {');
  FPack.Add('      currentNode = currentNode.host;');
  FPack.Add('    }');
  FPack.Add('');
  FPack.Add('    while (isHTMLElement(currentNode) && [''html'', ''body''].indexOf(getNodeName(currentNode)) < 0) {');
  FPack.Add('      var css = getComputedStyle(currentNode); // This is non-exhaustive but covers the most common CSS properties that');
  FPack.Add('      // create a containing block.');
  FPack.Add('      // https://developer.mozilla.org/en-US/docs/Web/CSS/Containing_block#identifying_the_containing_block');
  FPack.Add('');
  FPack.Add('      if (css.transform !== ''none'' || css.perspective !== ''none'' || css.contain === ''paint'' || [''transform'', ''perspective''].indexOf(css.willChange) !== -1 || isFirefox && css.willChange === ''filter'' || isFirefox && css.filter && css.filte'+'r !== ''none'') {');
  FPack.Add('        return currentNode;');
  FPack.Add('      } else {');
  FPack.Add('        currentNode = currentNode.parentNode;');
  FPack.Add('      }');
  FPack.Add('    }');
  FPack.Add('');
  FPack.Add('    return null;');
  FPack.Add('  } // Gets the closest ancestor positioned element. Handles some edge cases,');
  FPack.Add('  // such as table ancestors and cross browser bugs.');
  FPack.Add('');
  FPack.Add('');
  FPack.Add('  function getOffsetParent(element) {');
  FPack.Add('    var window = getWindow(element);');
  FPack.Add('    var offsetParent = getTrueOffsetParent(element);');
  FPack.Add('');
  FPack.Add('    while (offsetParent && isTableElement(offsetParent) && getComputedStyle(offsetParent).position === ''static'') {');
  FPack.Add('      offsetParent = getTrueOffsetParent(offsetParent);');
  FPack.Add('    }');
  FPack.Add('');
  FPack.Add('    if (offsetParent && (getNodeName(offsetParent) === ''html'' || getNodeName(offsetParent) === ''body'' && getComputedStyle(offsetParent).position === ''static'')) {');
end;

procedure TPopperJS.PopperJS_2;
begin
  FPack.Add('      return window;');
  FPack.Add('    }');
  FPack.Add('');
  FPack.Add('    return offsetParent || getContainingBlock(element) || window;');
  FPack.Add('  }');
  FPack.Add('');
  FPack.Add('  var top = ''top'';');
  FPack.Add('  var bottom = ''bottom'';');
  FPack.Add('  var right = ''right'';');
  FPack.Add('  var left = ''left'';');
  FPack.Add('  var auto = ''auto'';');
  FPack.Add('  var basePlacements = [top, bottom, right, left];');
  FPack.Add('  var start = ''start'';');
  FPack.Add('  var end = ''end'';');
  FPack.Add('  var clippingParents = ''clippingParents'';');
  FPack.Add('  var viewport = ''viewport'';');
  FPack.Add('  var popper = ''popper'';');
  FPack.Add('  var reference = ''reference'';');
  FPack.Add('  var variationPlacements = /*#__PURE__*/basePlacements.reduce(function (acc, placement) {');
  FPack.Add('    return acc.concat([placement + "-" + start, placement + "-" + end]);');
  FPack.Add('  }, []);');
  FPack.Add('  var placements = /*#__PURE__*/[].concat(basePlacements, [auto]).reduce(function (acc, placement) {');
  FPack.Add('    return acc.concat([placement, placement + "-" + start, placement + "-" + end]);');
  FPack.Add('  }, []); // modifiers that need to read the DOM');
  FPack.Add('');
  FPack.Add('  var beforeRead = ''beforeRead'';');
  FPack.Add('  var read = ''read'';');
  FPack.Add('  var afterRead = ''afterRead''; // pure-logic modifiers');
  FPack.Add('');
  FPack.Add('  var beforeMain = ''beforeMain'';');
  FPack.Add('  var main = ''main'';');
  FPack.Add('  var afterMain = ''afterMain''; // modifier with the purpose to write to the DOM (or write into a framework state)');
  FPack.Add('');
  FPack.Add('  var beforeWrite = ''beforeWrite'';');
  FPack.Add('  var write = ''write'';');
  FPack.Add('  var afterWrite = ''afterWrite'';');
  FPack.Add('  var modifierPhases = [beforeRead, read, afterRead, beforeMain, main, afterMain, beforeWrite, write, afterWrite];');
  FPack.Add('');
  FPack.Add('  function order(modifiers) {');
  FPack.Add('    var map = new Map();');
  FPack.Add('    var visited = new Set();');
  FPack.Add('    var result = [];');
  FPack.Add('    modifiers.forEach(function (modifier) {');
  FPack.Add('      map.set(modifier.name, modifier);');
  FPack.Add('    }); // On visiting object, check for its dependencies and visit them recursively');
  FPack.Add('');
  FPack.Add('    function sort(modifier) {');
  FPack.Add('      visited.add(modifier.name);');
  FPack.Add('      var requires = [].concat(modifier.requires || [], modifier.requiresIfExists || []);');
  FPack.Add('      requires.forEach(function (dep) {');
  FPack.Add('        if (!visited.has(dep)) {');
  FPack.Add('          var depModifier = map.get(dep);');
  FPack.Add('');
  FPack.Add('          if (depModifier) {');
  FPack.Add('            sort(depModifier);');
  FPack.Add('          }');
  FPack.Add('        }');
  FPack.Add('      });');
  FPack.Add('      result.push(modifier);');
  FPack.Add('    }');
  FPack.Add('');
  FPack.Add('    modifiers.forEach(function (modifier) {');
  FPack.Add('      if (!visited.has(modifier.name)) {');
  FPack.Add('        // check for visited object');
  FPack.Add('        sort(modifier);');
  FPack.Add('      }');
  FPack.Add('    });');
  FPack.Add('    return result;');
  FPack.Add('  }');
  FPack.Add('');
  FPack.Add('  function orderModifiers(modifiers) {');
  FPack.Add('    // order based on dependencies');
  FPack.Add('    var orderedModifiers = order(modifiers); // order based on phase');
  FPack.Add('');
  FPack.Add('    return modifierPhases.reduce(function (acc, phase) {');
  FPack.Add('      return acc.concat(orderedModifiers.filter(function (modifier) {');
  FPack.Add('        return modifier.phase === phase;');
  FPack.Add('      }));');
  FPack.Add('    }, []);');
  FPack.Add('  }');
  FPack.Add('');
  FPack.Add('  function debounce(fn) {');
  FPack.Add('    var pending;');
  FPack.Add('    return function () {');
  FPack.Add('      if (!pending) {');
  FPack.Add('        pending = new Promise(function (resolve) {');
  FPack.Add('          Promise.resolve().then(function () {');
  FPack.Add('            pending = undefined;');
  FPack.Add('            resolve(fn());');
  FPack.Add('          });');
  FPack.Add('        });');
  FPack.Add('      }');
  FPack.Add('');
  FPack.Add('      return pending;');
  FPack.Add('    };');
  FPack.Add('  }');
  FPack.Add('');
  FPack.Add('  function mergeByName(modifiers) {');
  FPack.Add('    var merged = modifiers.reduce(function (merged, current) {');
  FPack.Add('      var existing = merged[current.name];');
  FPack.Add('      merged[current.name] = existing ? Object.assign({}, existing, current, {');
  FPack.Add('        options: Object.assign({}, existing.options, current.options),');
  FPack.Add('        data: Object.assign({}, existing.data, current.data)');
  FPack.Add('      }) : current;');
  FPack.Add('      return merged;');
  FPack.Add('    }, {}); // IE11 does not support Object.values');
  FPack.Add('');
  FPack.Add('    return Object.keys(merged).map(function (key) {');
  FPack.Add('      return merged[key];');
  FPack.Add('    });');
  FPack.Add('  }');
  FPack.Add('');
  FPack.Add('  function getViewportRect(element, strategy) {');
  FPack.Add('    var win = getWindow(element);');
  FPack.Add('    var html = getDocumentElement(element);');
  FPack.Add('    var visualViewport = win.visualViewport;');
  FPack.Add('    var width = html.clientWidth;');
  FPack.Add('    var height = html.clientHeight;');
  FPack.Add('    var x = 0;');
  FPack.Add('    var y = 0;');
  FPack.Add('');
  FPack.Add('    if (visualViewport) {');
  FPack.Add('      width = visualViewport.width;');
  FPack.Add('      height = visualViewport.height;');
  FPack.Add('      var layoutViewport = isLayoutViewport();');
  FPack.Add('');
  FPack.Add('      if (layoutViewport || !layoutViewport && strategy === ''fixed'') {');
  FPack.Add('        x = visualViewport.offsetLeft;');
  FPack.Add('        y = visualViewport.offsetTop;');
  FPack.Add('      }');
  FPack.Add('    }');
  FPack.Add('');
  FPack.Add('    return {');
  FPack.Add('      width: width,');
  FPack.Add('      height: height,');
  FPack.Add('      x: x + getWindowScrollBarX(element),');
  FPack.Add('      y: y');
  FPack.Add('    };');
  FPack.Add('  }');
  FPack.Add('');
  FPack.Add('  // of the `<html>` and `<body>` rect bounds if horizontally scrollable');
  FPack.Add('');
  FPack.Add('  function getDocumentRect(element) {');
  FPack.Add('    var _element$ownerDocumen;');
  FPack.Add('');
  FPack.Add('    var html = getDocumentElement(element);');
  FPack.Add('    var winScroll = getWindowScroll(element);');
  FPack.Add('    var body = (_element$ownerDocumen = element.ownerDocument) == null ? void 0 : _element$ownerDocumen.body;');
  FPack.Add('    var width = max(html.scrollWidth, html.clientWidth, body ? body.scrollWidth : 0, body ? body.clientWidth : 0);');
  FPack.Add('    var height = max(html.scrollHeight, html.clientHeight, body ? body.scrollHeight : 0, body ? body.clientHeight : 0);');
  FPack.Add('    var x = -winScroll.scrollLeft + getWindowScrollBarX(element);');
  FPack.Add('    var y = -winScroll.scrollTop;');
  FPack.Add('');
  FPack.Add('    if (getComputedStyle(body || html).direction === ''rtl'') {');
  FPack.Add('      x += max(html.clientWidth, body ? body.clientWidth : 0) - width;');
  FPack.Add('    }');
  FPack.Add('');
  FPack.Add('    return {');
  FPack.Add('      width: width,');
  FPack.Add('      height: height,');
  FPack.Add('      x: x,');
  FPack.Add('      y: y');
  FPack.Add('    };');
  FPack.Add('  }');
  FPack.Add('');
  FPack.Add('  function contains(parent, child) {');
  FPack.Add('    var rootNode = child.getRootNode && child.getRootNode(); // First, attempt with faster native method');
  FPack.Add('');
  FPack.Add('    if (parent.contains(child)) {');
  FPack.Add('      return true;');
  FPack.Add('    } // then fallback to custom implementation with Shadow DOM support');
  FPack.Add('    else if (rootNode && isShadowRoot(rootNode)) {');
  FPack.Add('        var next = child;');
  FPack.Add('');
  FPack.Add('        do {');
  FPack.Add('          if (next && parent.isSameNode(next)) {');
  FPack.Add('            return true;');
  FPack.Add('          } // $FlowFixMe[prop-missing]: need a better way to handle this...');
  FPack.Add('');
  FPack.Add('');
  FPack.Add('          next = next.parentNode || next.host;');
  FPack.Add('        } while (next);');
  FPack.Add('      } // Give up, the result is false');
  FPack.Add('');
  FPack.Add('');
  FPack.Add('    return false;');
  FPack.Add('  }');
  FPack.Add('');
  FPack.Add('  function rectToClientRect(rect) {');
  FPack.Add('    return Object.assign({}, rect, {');
  FPack.Add('      left: rect.x,');
  FPack.Add('      top: rect.y,');
  FPack.Add('      right: rect.x + rect.width,');
  FPack.Add('      bottom: rect.y + rect.height');
  FPack.Add('    });');
  FPack.Add('  }');
  FPack.Add('');
  FPack.Add('  function getInnerBoundingClientRect(element, strategy) {');
  FPack.Add('    var rect = getBoundingClientRect(element, false, strategy === ''fixed'');');
  FPack.Add('    rect.top = rect.top + element.clientTop;');
  FPack.Add('    rect.left = rect.left + element.clientLeft;');
  FPack.Add('    rect.bottom = rect.top + element.clientHeight;');
  FPack.Add('    rect.right = rect.left + element.clientWidth;');
  FPack.Add('    rect.width = element.clientWidth;');
  FPack.Add('    rect.height = element.clientHeight;');
  FPack.Add('    rect.x = rect.left;');
  FPack.Add('    rect.y = rect.top;');
  FPack.Add('    return rect;');
  FPack.Add('  }');
  FPack.Add('');
  FPack.Add('  function getClientRectFromMixedType(element, clippingParent, strategy) {');
  FPack.Add('    return clippingParent === viewport ? rectToClientRect(getViewportRect(element, strategy)) : isElement(clippingParent) ? getInnerBoundingClientRect(clippingParent, strategy) : rectToClientRect(getDocumentRect(getDocumentElement(element)));');
  FPack.Add('  } // A "clipping parent" is an overflowable container with the characteristic of');
  FPack.Add('  // clipping (or hiding) overflowing elements with a position different from');
  FPack.Add('  // `initial`');
  FPack.Add('');
  FPack.Add('');
  FPack.Add('  function getClippingParents(element) {');
  FPack.Add('    var clippingParents = listScrollParents(getParentNode(element));');
  FPack.Add('    var canEscapeClipping = [''absolute'', ''fixed''].indexOf(getComputedStyle(element).position) >= 0;');
  FPack.Add('    var clipperElement = canEscapeClipping && isHTMLElement(element) ? getOffsetParent(element) : element;');
  FPack.Add('');
  FPack.Add('    if (!isElement(clipperElement)) {');
  FPack.Add('      return [];');
  FPack.Add('    } // $FlowFixMe[incompatible-return]: https://github.com/facebook/flow/issues/1414');
  FPack.Add('');
  FPack.Add('');
  FPack.Add('    return clippingParents.filter(function (clippingParent) {');
  FPack.Add('      return isElement(clippingParent) && contains(clippingParent, clipperElement) && getNodeName(clippingParent) !== ''body'';');
  FPack.Add('    });');
  FPack.Add('  } // Gets the maximum area that the element is visible in due to any number of');
  FPack.Add('  // clipping parents');
  FPack.Add('');
  FPack.Add('');
  FPack.Add('  function getClippingRect(element, boundary, rootBoundary, strategy) {');
  FPack.Add('    var mainClippingParents = boundary === ''clippingParents'' ? getClippingParents(element) : [].concat(boundary);');
  FPack.Add('    var clippingParents = [].concat(mainClippingParents, [rootBoundary]);');
  FPack.Add('    var firstClippingParent = clippingParents[0];');
  FPack.Add('    var clippingRect = clippingParents.reduce(function (accRect, clippingParent) {');
  FPack.Add('      var rect = getClientRectFromMixedType(element, clippingParent, strategy);');
  FPack.Add('      accRect.top = max(rect.top, accRect.top);');
  FPack.Add('      accRect.right = min(rect.right, accRect.right);');
  FPack.Add('      accRect.bottom = min(rect.bottom, accRect.bottom);');
  FPack.Add('      accRect.left = max(rect.left, accRect.left);');
  FPack.Add('      return accRect;');
  FPack.Add('    }, getClientRectFromMixedType(element, firstClippingParent, strategy));');
  FPack.Add('    clippingRect.width = clippingRect.right - clippingRect.left;');
  FPack.Add('    clippingRect.height = clippingRect.bottom - clippingRect.top;');
  FPack.Add('    clippingRect.x = clippingRect.left;');
  FPack.Add('    clippingRect.y = clippingRect.top;');
  FPack.Add('    return clippingRect;');
  FPack.Add('  }');
  FPack.Add('');
  FPack.Add('  function getBasePlacement(placement) {');
  FPack.Add('    return placement.split(''-'')[0];');
  FPack.Add('  }');
  FPack.Add('');
  FPack.Add('  function getVariation(placement) {');
  FPack.Add('    return placement.split(''-'')[1];');
  FPack.Add('  }');
  FPack.Add('');
  FPack.Add('  function getMainAxisFromPlacement(placement) {');
  FPack.Add('    return [''top'', ''bottom''].indexOf(placement) >= 0 ? ''x'' : ''y'';');
  FPack.Add('  }');
  FPack.Add('');
  FPack.Add('  function computeOffsets(_ref) {');
  FPack.Add('    var reference = _ref.reference,');
  FPack.Add('        element = _ref.element,');
  FPack.Add('        placement = _ref.placement;');
  FPack.Add('    var basePlacement = placement ? getBasePlacement(placement) : null;');
  FPack.Add('    var variation = placement ? getVariation(placement) : null;');
  FPack.Add('    var commonX = reference.x + reference.width / 2 - element.width / 2;');
  FPack.Add('    var commonY = reference.y + reference.height / 2 - element.height / 2;');
  FPack.Add('    var offsets;');
  FPack.Add('');
  FPack.Add('    switch (basePlacement) {');
  FPack.Add('      case top:');
  FPack.Add('        offsets = {');
  FPack.Add('          x: commonX,');
  FPack.Add('          y: reference.y - element.height');
  FPack.Add('        };');
  FPack.Add('        break;');
  FPack.Add('');
  FPack.Add('      case bottom:');
  FPack.Add('        offsets = {');
  FPack.Add('          x: commonX,');
  FPack.Add('          y: reference.y + reference.height');
  FPack.Add('        };');
  FPack.Add('        break;');
  FPack.Add('');
  FPack.Add('      case right:');
  FPack.Add('        offsets = {');
  FPack.Add('          x: reference.x + reference.width,');
  FPack.Add('          y: commonY');
  FPack.Add('        };');
  FPack.Add('        break;');
  FPack.Add('');
  FPack.Add('      case left:');
  FPack.Add('        offsets = {');
  FPack.Add('          x: reference.x - element.width,');
  FPack.Add('          y: commonY');
  FPack.Add('        };');
  FPack.Add('        break;');
  FPack.Add('');
  FPack.Add('      default:');
  FPack.Add('        offsets = {');
  FPack.Add('          x: reference.x,');
  FPack.Add('          y: reference.y');
  FPack.Add('        };');
  FPack.Add('    }');
  FPack.Add('');
  FPack.Add('    var mainAxis = basePlacement ? getMainAxisFromPlacement(basePlacement) : null;');
  FPack.Add('');
  FPack.Add('    if (mainAxis != null) {');
  FPack.Add('      var len = mainAxis === ''y'' ? ''height'' : ''width'';');
  FPack.Add('');
  FPack.Add('      switch (variation) {');
  FPack.Add('        case start:');
  FPack.Add('          offsets[mainAxis] = offsets[mainAxis] - (reference[len] / 2 - element[len] / 2);');
  FPack.Add('          break;');
  FPack.Add('');
  FPack.Add('        case end:');
  FPack.Add('          offsets[mainAxis] = offsets[mainAxis] + (reference[len] / 2 - element[len] / 2);');
  FPack.Add('          break;');
  FPack.Add('      }');
  FPack.Add('    }');
  FPack.Add('');
  FPack.Add('    return offsets;');
  FPack.Add('  }');
  FPack.Add('');
  FPack.Add('  function getFreshSideObject() {');
  FPack.Add('    return {');
  FPack.Add('      top: 0,');
  FPack.Add('      right: 0,');
  FPack.Add('      bottom: 0,');
  FPack.Add('      left: 0');
  FPack.Add('    };');
  FPack.Add('  }');
  FPack.Add('');
  FPack.Add('  function mergePaddingObject(paddingObject) {');
  FPack.Add('    return Object.assign({}, getFreshSideObject(), paddingObject);');
  FPack.Add('  }');
  FPack.Add('');
  FPack.Add('  function expandToHashMap(value, keys) {');
  FPack.Add('    return keys.reduce(function (hashMap, key) {');
  FPack.Add('      hashMap[key] = value;');
  FPack.Add('      return hashMap;');
  FPack.Add('    }, {});');
  FPack.Add('  }');
  FPack.Add('');
end;

procedure TPopperJS.PopperJS_3;
begin
  FPack.Add('  function detectOverflow(state, options) {');
  FPack.Add('    if (options === void 0) {');
  FPack.Add('      options = {};');
  FPack.Add('    }');
  FPack.Add('');
  FPack.Add('    var _options = options,');
  FPack.Add('        _options$placement = _options.placement,');
  FPack.Add('        placement = _options$placement === void 0 ? state.placement : _options$placement,');
  FPack.Add('        _options$strategy = _options.strategy,');
  FPack.Add('        strategy = _options$strategy === void 0 ? state.strategy : _options$strategy,');
  FPack.Add('        _options$boundary = _options.boundary,');
  FPack.Add('        boundary = _options$boundary === void 0 ? clippingParents : _options$boundary,');
  FPack.Add('        _options$rootBoundary = _options.rootBoundary,');
  FPack.Add('        rootBoundary = _options$rootBoundary === void 0 ? viewport : _options$rootBoundary,');
  FPack.Add('        _options$elementConte = _options.elementContext,');
  FPack.Add('        elementContext = _options$elementConte === void 0 ? popper : _options$elementConte,');
  FPack.Add('        _options$altBoundary = _options.altBoundary,');
  FPack.Add('        altBoundary = _options$altBoundary === void 0 ? false : _options$altBoundary,');
  FPack.Add('        _options$padding = _options.padding,');
  FPack.Add('        padding = _options$padding === void 0 ? 0 : _options$padding;');
  FPack.Add('    var paddingObject = mergePaddingObject(typeof padding !== ''number'' ? padding : expandToHashMap(padding, basePlacements));');
  FPack.Add('    var altContext = elementContext === popper ? reference : popper;');
  FPack.Add('    var popperRect = state.rects.popper;');
  FPack.Add('    var element = state.elements[altBoundary ? altContext : elementContext];');
  FPack.Add('    var clippingClientRect = getClippingRect(isElement(element) ? element : element.contextElement || getDocumentElement(state.elements.popper), boundary, rootBoundary, strategy);');
  FPack.Add('    var referenceClientRect = getBoundingClientRect(state.elements.reference);');
  FPack.Add('    var popperOffsets = computeOffsets({');
  FPack.Add('      reference: referenceClientRect,');
  FPack.Add('      element: popperRect,');
  FPack.Add('      strategy: ''absolute'',');
  FPack.Add('      placement: placement');
  FPack.Add('    });');
  FPack.Add('    var popperClientRect = rectToClientRect(Object.assign({}, popperRect, popperOffsets));');
  FPack.Add('    var elementClientRect = elementContext === popper ? popperClientRect : referenceClientRect; // positive = overflowing the clipping rect');
  FPack.Add('    // 0 or negative = within the clipping rect');
  FPack.Add('');
  FPack.Add('    var overflowOffsets = {');
  FPack.Add('      top: clippingClientRect.top - elementClientRect.top + paddingObject.top,');
  FPack.Add('      bottom: elementClientRect.bottom - clippingClientRect.bottom + paddingObject.bottom,');
  FPack.Add('      left: clippingClientRect.left - elementClientRect.left + paddingObject.left,');
  FPack.Add('      right: elementClientRect.right - clippingClientRect.right + paddingObject.right');
  FPack.Add('    };');
  FPack.Add('    var offsetData = state.modifiersData.offset; // Offsets can be applied only to the popper element');
  FPack.Add('');
  FPack.Add('    if (elementContext === popper && offsetData) {');
  FPack.Add('      var offset = offsetData[placement];');
  FPack.Add('      Object.keys(overflowOffsets).forEach(function (key) {');
  FPack.Add('        var multiply = [right, bottom].indexOf(key) >= 0 ? 1 : -1;');
  FPack.Add('        var axis = [top, bottom].indexOf(key) >= 0 ? ''y'' : ''x'';');
  FPack.Add('        overflowOffsets[key] += offset[axis] * multiply;');
  FPack.Add('      });');
  FPack.Add('    }');
  FPack.Add('');
  FPack.Add('    return overflowOffsets;');
  FPack.Add('  }');
  FPack.Add('');
  FPack.Add('  var DEFAULT_OPTIONS = {');
  FPack.Add('    placement: ''bottom'',');
  FPack.Add('    modifiers: [],');
  FPack.Add('    strategy: ''absolute''');
  FPack.Add('  };');
  FPack.Add('');
  FPack.Add('  function areValidElements() {');
  FPack.Add('    for (var _len = arguments.length, args = new Array(_len), _key = 0; _key < _len; _key++) {');
  FPack.Add('      args[_key] = arguments[_key];');
  FPack.Add('    }');
  FPack.Add('');
  FPack.Add('    return !args.some(function (element) {');
  FPack.Add('      return !(element && typeof element.getBoundingClientRect === ''function'');');
  FPack.Add('    });');
  FPack.Add('  }');
  FPack.Add('');
  FPack.Add('  function popperGenerator(generatorOptions) {');
  FPack.Add('    if (generatorOptions === void 0) {');
  FPack.Add('      generatorOptions = {};');
  FPack.Add('    }');
  FPack.Add('');
  FPack.Add('    var _generatorOptions = generatorOptions,');
  FPack.Add('        _generatorOptions$def = _generatorOptions.defaultModifiers,');
  FPack.Add('        defaultModifiers = _generatorOptions$def === void 0 ? [] : _generatorOptions$def,');
  FPack.Add('        _generatorOptions$def2 = _generatorOptions.defaultOptions,');
  FPack.Add('        defaultOptions = _generatorOptions$def2 === void 0 ? DEFAULT_OPTIONS : _generatorOptions$def2;');
  FPack.Add('    return function createPopper(reference, popper, options) {');
  FPack.Add('      if (options === void 0) {');
  FPack.Add('        options = defaultOptions;');
  FPack.Add('      }');
  FPack.Add('');
  FPack.Add('      var state = {');
  FPack.Add('        placement: ''bottom'',');
  FPack.Add('        orderedModifiers: [],');
  FPack.Add('        options: Object.assign({}, DEFAULT_OPTIONS, defaultOptions),');
  FPack.Add('        modifiersData: {},');
  FPack.Add('        elements: {');
  FPack.Add('          reference: reference,');
  FPack.Add('          popper: popper');
  FPack.Add('        },');
  FPack.Add('        attributes: {},');
  FPack.Add('        styles: {}');
  FPack.Add('      };');
  FPack.Add('      var effectCleanupFns = [];');
  FPack.Add('      var isDestroyed = false;');
  FPack.Add('      var instance = {');
  FPack.Add('        state: state,');
  FPack.Add('        setOptions: function setOptions(setOptionsAction) {');
  FPack.Add('          var options = typeof setOptionsAction === ''function'' ? setOptionsAction(state.options) : setOptionsAction;');
  FPack.Add('          cleanupModifierEffects();');
  FPack.Add('          state.options = Object.assign({}, defaultOptions, state.options, options);');
  FPack.Add('          state.scrollParents = {');
  FPack.Add('            reference: isElement(reference) ? listScrollParents(reference) : reference.contextElement ? listScrollParents(reference.contextElement) : [],');
  FPack.Add('            popper: listScrollParents(popper)');
  FPack.Add('          }; // Orders the modifiers based on their dependencies and `phase`');
  FPack.Add('          // properties');
  FPack.Add('');
  FPack.Add('          var orderedModifiers = orderModifiers(mergeByName([].concat(defaultModifiers, state.options.modifiers))); // Strip out disabled modifiers');
  FPack.Add('');
  FPack.Add('          state.orderedModifiers = orderedModifiers.filter(function (m) {');
  FPack.Add('            return m.enabled;');
  FPack.Add('          });');
  FPack.Add('          runModifierEffects();');
  FPack.Add('          return instance.update();');
  FPack.Add('        },');
  FPack.Add('        // Sync update – it will always be executed, even if not necessary. This');
  FPack.Add('        // is useful for low frequency updates where sync behavior simplifies the');
  FPack.Add('        // logic.');
  FPack.Add('        // For high frequency updates (e.g. `resize` and `scroll` events), always');
  FPack.Add('        // prefer the async Popper#update method');
  FPack.Add('        forceUpdate: function forceUpdate() {');
  FPack.Add('          if (isDestroyed) {');
  FPack.Add('            return;');
  FPack.Add('          }');
  FPack.Add('');
  FPack.Add('          var _state$elements = state.elements,');
  FPack.Add('              reference = _state$elements.reference,');
  FPack.Add('              popper = _state$elements.popper; // Don''t proceed if `reference` or `popper` are not valid elements');
  FPack.Add('          // anymore');
  FPack.Add('');
  FPack.Add('          if (!areValidElements(reference, popper)) {');
  FPack.Add('            return;');
  FPack.Add('          } // Store the reference and popper rects to be read by modifiers');
  FPack.Add('');
  FPack.Add('');
  FPack.Add('          state.rects = {');
  FPack.Add('            reference: getCompositeRect(reference, getOffsetParent(popper), state.options.strategy === ''fixed''),');
  FPack.Add('            popper: getLayoutRect(popper)');
  FPack.Add('          }; // Modifiers have the ability to reset the current update cycle. The');
  FPack.Add('          // most common use case for this is the `flip` modifier changing the');
  FPack.Add('          // placement, which then needs to re-run all the modifiers, because the');
  FPack.Add('          // logic was previously ran for the previous placement and is therefore');
  FPack.Add('          // stale/incorrect');
  FPack.Add('');
  FPack.Add('          state.reset = false;');
  FPack.Add('          state.placement = state.options.placement; // On each update cycle, the `modifiersData` property for each modifier');
  FPack.Add('          // is filled with the initial data specified by the modifier. This means');
  FPack.Add('          // it doesn''t persist and is fresh on each update.');
  FPack.Add('          // To ensure persistent data, use `${name}#persistent`');
  FPack.Add('');
  FPack.Add('          state.orderedModifiers.forEach(function (modifier) {');
  FPack.Add('            return state.modifiersData[modifier.name] = Object.assign({}, modifier.data);');
  FPack.Add('          });');
  FPack.Add('');
  FPack.Add('          for (var index = 0; index < state.orderedModifiers.length; index++) {');
  FPack.Add('            if (state.reset === true) {');
  FPack.Add('              state.reset = false;');
  FPack.Add('              index = -1;');
  FPack.Add('              continue;');
  FPack.Add('            }');
  FPack.Add('');
  FPack.Add('            var _state$orderedModifie = state.orderedModifiers[index],');
  FPack.Add('                fn = _state$orderedModifie.fn,');
  FPack.Add('                _state$orderedModifie2 = _state$orderedModifie.options,');
  FPack.Add('                _options = _state$orderedModifie2 === void 0 ? {} : _state$orderedModifie2,');
  FPack.Add('                name = _state$orderedModifie.name;');
  FPack.Add('');
  FPack.Add('            if (typeof fn === ''function'') {');
  FPack.Add('              state = fn({');
  FPack.Add('                state: state,');
  FPack.Add('                options: _options,');
  FPack.Add('                name: name,');
  FPack.Add('                instance: instance');
  FPack.Add('              }) || state;');
  FPack.Add('            }');
  FPack.Add('          }');
  FPack.Add('        },');
  FPack.Add('        // Async and optimistically optimized update – it will not be executed if');
  FPack.Add('        // not necessary (debounced to run at most once-per-tick)');
  FPack.Add('        update: debounce(function () {');
  FPack.Add('          return new Promise(function (resolve) {');
  FPack.Add('            instance.forceUpdate();');
  FPack.Add('            resolve(state);');
  FPack.Add('          });');
  FPack.Add('        }),');
  FPack.Add('        destroy: function destroy() {');
  FPack.Add('          cleanupModifierEffects();');
  FPack.Add('          isDestroyed = true;');
  FPack.Add('        }');
  FPack.Add('      };');
  FPack.Add('');
  FPack.Add('      if (!areValidElements(reference, popper)) {');
  FPack.Add('        return instance;');
  FPack.Add('      }');
  FPack.Add('');
  FPack.Add('      instance.setOptions(options).then(function (state) {');
  FPack.Add('        if (!isDestroyed && options.onFirstUpdate) {');
  FPack.Add('          options.onFirstUpdate(state);');
  FPack.Add('        }');
  FPack.Add('      }); // Modifiers have the ability to execute arbitrary code before the first');
  FPack.Add('      // update cycle runs. They will be executed in the same order as the update');
  FPack.Add('      // cycle. This is useful when a modifier adds some persistent data that');
  FPack.Add('      // other modifiers need to use, but the modifier is run after the dependent');
  FPack.Add('      // one.');
  FPack.Add('');
  FPack.Add('      function runModifierEffects() {');
  FPack.Add('        state.orderedModifiers.forEach(function (_ref) {');
  FPack.Add('          var name = _ref.name,');
  FPack.Add('              _ref$options = _ref.options,');
  FPack.Add('              options = _ref$options === void 0 ? {} : _ref$options,');
  FPack.Add('              effect = _ref.effect;');
  FPack.Add('');
  FPack.Add('          if (typeof effect === ''function'') {');
  FPack.Add('            var cleanupFn = effect({');
  FPack.Add('              state: state,');
  FPack.Add('              name: name,');
  FPack.Add('              instance: instance,');
  FPack.Add('              options: options');
  FPack.Add('            });');
  FPack.Add('');
  FPack.Add('            var noopFn = function noopFn() {};');
  FPack.Add('');
  FPack.Add('            effectCleanupFns.push(cleanupFn || noopFn);');
  FPack.Add('          }');
  FPack.Add('        });');
  FPack.Add('      }');
  FPack.Add('');
  FPack.Add('      function cleanupModifierEffects() {');
  FPack.Add('        effectCleanupFns.forEach(function (fn) {');
  FPack.Add('          return fn();');
  FPack.Add('        });');
  FPack.Add('        effectCleanupFns = [];');
  FPack.Add('      }');
  FPack.Add('');
  FPack.Add('      return instance;');
  FPack.Add('    };');
  FPack.Add('  }');
  FPack.Add('');
  FPack.Add('  var passive = {');
  FPack.Add('    passive: true');
  FPack.Add('  };');
  FPack.Add('');
  FPack.Add('  function effect$2(_ref) {');
  FPack.Add('    var state = _ref.state,');
  FPack.Add('        instance = _ref.instance,');
  FPack.Add('        options = _ref.options;');
  FPack.Add('    var _options$scroll = options.scroll,');
  FPack.Add('        scroll = _options$scroll === void 0 ? true : _options$scroll,');
  FPack.Add('        _options$resize = options.resize,');
  FPack.Add('        resize = _options$resize === void 0 ? true : _options$resize;');
  FPack.Add('    var window = getWindow(state.elements.popper);');
  FPack.Add('    var scrollParents = [].concat(state.scrollParents.reference, state.scrollParents.popper);');
  FPack.Add('');
  FPack.Add('    if (scroll) {');
  FPack.Add('      scrollParents.forEach(function (scrollParent) {');
  FPack.Add('        scrollParent.addEventListener(''scroll'', instance.update, passive);');
  FPack.Add('      });');
  FPack.Add('    }');
  FPack.Add('');
  FPack.Add('    if (resize) {');
  FPack.Add('      window.addEventListener(''resize'', instance.update, passive);');
  FPack.Add('    }');
  FPack.Add('');
  FPack.Add('    return function () {');
  FPack.Add('      if (scroll) {');
  FPack.Add('        scrollParents.forEach(function (scrollParent) {');
  FPack.Add('          scrollParent.removeEventListener(''scroll'', instance.update, passive);');
  FPack.Add('        });');
  FPack.Add('      }');
  FPack.Add('');
  FPack.Add('      if (resize) {');
  FPack.Add('        window.removeEventListener(''resize'', instance.update, passive);');
  FPack.Add('      }');
  FPack.Add('    };');
  FPack.Add('  } // eslint-disable-next-line import/no-unused-modules');
  FPack.Add('');
  FPack.Add('');
  FPack.Add('  var eventListeners = {');
  FPack.Add('    name: ''eventListeners'',');
  FPack.Add('    enabled: true,');
  FPack.Add('    phase: ''write'',');
  FPack.Add('    fn: function fn() {},');
  FPack.Add('    effect: effect$2,');
  FPack.Add('    data: {}');
  FPack.Add('  };');
  FPack.Add('');
  FPack.Add('  function popperOffsets(_ref) {');
  FPack.Add('    var state = _ref.state,');
  FPack.Add('        name = _ref.name;');
  FPack.Add('    // Offsets are the actual position the popper needs to have to be');
  FPack.Add('    // properly positioned near its reference element');
  FPack.Add('    // This is the most basic placement, and will be adjusted by');
  FPack.Add('    // the modifiers in the next step');
  FPack.Add('    state.modifiersData[name] = computeOffsets({');
  FPack.Add('      reference: state.rects.reference,');
  FPack.Add('      element: state.rects.popper,');
  FPack.Add('      strategy: ''absolute'',');
  FPack.Add('      placement: state.placement');
  FPack.Add('    });');
  FPack.Add('  } // eslint-disable-next-line import/no-unused-modules');
  FPack.Add('');
  FPack.Add('');
  FPack.Add('  var popperOffsets$1 = {');
  FPack.Add('    name: ''popperOffsets'',');
  FPack.Add('    enabled: true,');
  FPack.Add('    phase: ''read'',');
  FPack.Add('    fn: popperOffsets,');
  FPack.Add('    data: {}');
  FPack.Add('  };');
  FPack.Add('');
  FPack.Add('  var unsetSides = {');
  FPack.Add('    top: ''auto'',');
  FPack.Add('    right: ''auto'',');
  FPack.Add('    bottom: ''auto'',');
  FPack.Add('    left: ''auto''');
  FPack.Add('  }; // Round the offsets to the nearest suitable subpixel based on the DPR.');
  FPack.Add('  // Zooming can change the DPR, but it seems to report a value that will');
  FPack.Add('  // cleanly divide the values into the appropriate subpixels.');
  FPack.Add('');
  FPack.Add('  function roundOffsetsByDPR(_ref, win) {');
  FPack.Add('    var x = _ref.x,');
  FPack.Add('        y = _ref.y;');
  FPack.Add('    var dpr = win.devicePixelRatio || 1;');
  FPack.Add('    return {');
  FPack.Add('      x: round(x * dpr) / dpr || 0,');
  FPack.Add('      y: round(y * dpr) / dpr || 0');
  FPack.Add('    };');
  FPack.Add('  }');
  FPack.Add('');
  FPack.Add('  function mapToStyles(_ref2) {');
  FPack.Add('    var _Object$assign2;');
  FPack.Add('');
  FPack.Add('    var popper = _ref2.popper,');
  FPack.Add('        popperRect = _ref2.popperRect,');
  FPack.Add('        placement = _ref2.placement,');
  FPack.Add('        variation = _ref2.variation,');
  FPack.Add('        offsets = _ref2.offsets,');
  FPack.Add('        position = _ref2.position,');
  FPack.Add('        gpuAcceleration = _ref2.gpuAcceleration,');
  FPack.Add('        adaptive = _ref2.adaptive,');
  FPack.Add('        roundOffsets = _ref2.roundOffsets,');
  FPack.Add('        isFixed = _ref2.isFixed;');
  FPack.Add('    var _offsets$x = offsets.x,');
  FPack.Add('        x = _offsets$x === void 0 ? 0 : _offsets$x,');
end;

procedure TPopperJS.PopperJS_4;
begin
  FPack.Add('        _offsets$y = offsets.y,');
  FPack.Add('        y = _offsets$y === void 0 ? 0 : _offsets$y;');
  FPack.Add('');
  FPack.Add('    var _ref3 = typeof roundOffsets === ''function'' ? roundOffsets({');
  FPack.Add('      x: x,');
  FPack.Add('      y: y');
  FPack.Add('    }) : {');
  FPack.Add('      x: x,');
  FPack.Add('      y: y');
  FPack.Add('    };');
  FPack.Add('');
  FPack.Add('    x = _ref3.x;');
  FPack.Add('    y = _ref3.y;');
  FPack.Add('    var hasX = offsets.hasOwnProperty(''x'');');
  FPack.Add('    var hasY = offsets.hasOwnProperty(''y'');');
  FPack.Add('    var sideX = left;');
  FPack.Add('    var sideY = top;');
  FPack.Add('    var win = window;');
  FPack.Add('');
  FPack.Add('    if (adaptive) {');
  FPack.Add('      var offsetParent = getOffsetParent(popper);');
  FPack.Add('      var heightProp = ''clientHeight'';');
  FPack.Add('      var widthProp = ''clientWidth'';');
  FPack.Add('');
  FPack.Add('      if (offsetParent === getWindow(popper)) {');
  FPack.Add('        offsetParent = getDocumentElement(popper);');
  FPack.Add('');
  FPack.Add('        if (getComputedStyle(offsetParent).position !== ''static'' && position === ''absolute'') {');
  FPack.Add('          heightProp = ''scrollHeight'';');
  FPack.Add('          widthProp = ''scrollWidth'';');
  FPack.Add('        }');
  FPack.Add('      } // $FlowFixMe[incompatible-cast]: force type refinement, we compare offsetParent with window above, but Flow doesn''t detect it');
  FPack.Add('');
  FPack.Add('');
  FPack.Add('      offsetParent = offsetParent;');
  FPack.Add('');
  FPack.Add('      if (placement === top || (placement === left || placement === right) && variation === end) {');
  FPack.Add('        sideY = bottom;');
  FPack.Add('        var offsetY = isFixed && offsetParent === win && win.visualViewport ? win.visualViewport.height : // $FlowFixMe[prop-missing]');
  FPack.Add('        offsetParent[heightProp];');
  FPack.Add('        y -= offsetY - popperRect.height;');
  FPack.Add('        y *= gpuAcceleration ? 1 : -1;');
  FPack.Add('      }');
  FPack.Add('');
  FPack.Add('      if (placement === left || (placement === top || placement === bottom) && variation === end) {');
  FPack.Add('        sideX = right;');
  FPack.Add('        var offsetX = isFixed && offsetParent === win && win.visualViewport ? win.visualViewport.width : // $FlowFixMe[prop-missing]');
  FPack.Add('        offsetParent[widthProp];');
  FPack.Add('        x -= offsetX - popperRect.width;');
  FPack.Add('        x *= gpuAcceleration ? 1 : -1;');
  FPack.Add('      }');
  FPack.Add('    }');
  FPack.Add('');
  FPack.Add('    var commonStyles = Object.assign({');
  FPack.Add('      position: position');
  FPack.Add('    }, adaptive && unsetSides);');
  FPack.Add('');
  FPack.Add('    var _ref4 = roundOffsets === true ? roundOffsetsByDPR({');
  FPack.Add('      x: x,');
  FPack.Add('      y: y');
  FPack.Add('    }, getWindow(popper)) : {');
  FPack.Add('      x: x,');
  FPack.Add('      y: y');
  FPack.Add('    };');
  FPack.Add('');
  FPack.Add('    x = _ref4.x;');
  FPack.Add('    y = _ref4.y;');
  FPack.Add('');
  FPack.Add('    if (gpuAcceleration) {');
  FPack.Add('      var _Object$assign;');
  FPack.Add('');
  FPack.Add('      return Object.assign({}, commonStyles, (_Object$assign = {}, _Object$assign[sideY] = hasY ? ''0'' : '''', _Object$assign[sideX] = hasX ? ''0'' : '''', _Object$assign.transform = (win.devicePixelRatio || 1) <= 1 ? "translate(" + x + "px, " + y +'+' "px)" : "translate3d(" + x + "px, " + y + "px, 0)", _Object$assign));');
  FPack.Add('    }');
  FPack.Add('');
  FPack.Add('    return Object.assign({}, commonStyles, (_Object$assign2 = {}, _Object$assign2[sideY] = hasY ? y + "px" : '''', _Object$assign2[sideX] = hasX ? x + "px" : '''', _Object$assign2.transform = '''', _Object$assign2));');
  FPack.Add('  }');
  FPack.Add('');
  FPack.Add('  function computeStyles(_ref5) {');
  FPack.Add('    var state = _ref5.state,');
  FPack.Add('        options = _ref5.options;');
  FPack.Add('    var _options$gpuAccelerat = options.gpuAcceleration,');
  FPack.Add('        gpuAcceleration = _options$gpuAccelerat === void 0 ? true : _options$gpuAccelerat,');
  FPack.Add('        _options$adaptive = options.adaptive,');
  FPack.Add('        adaptive = _options$adaptive === void 0 ? true : _options$adaptive,');
  FPack.Add('        _options$roundOffsets = options.roundOffsets,');
  FPack.Add('        roundOffsets = _options$roundOffsets === void 0 ? true : _options$roundOffsets;');
  FPack.Add('    var commonStyles = {');
  FPack.Add('      placement: getBasePlacement(state.placement),');
  FPack.Add('      variation: getVariation(state.placement),');
  FPack.Add('      popper: state.elements.popper,');
  FPack.Add('      popperRect: state.rects.popper,');
  FPack.Add('      gpuAcceleration: gpuAcceleration,');
  FPack.Add('      isFixed: state.options.strategy === ''fixed''');
  FPack.Add('    };');
  FPack.Add('');
  FPack.Add('    if (state.modifiersData.popperOffsets != null) {');
  FPack.Add('      state.styles.popper = Object.assign({}, state.styles.popper, mapToStyles(Object.assign({}, commonStyles, {');
  FPack.Add('        offsets: state.modifiersData.popperOffsets,');
  FPack.Add('        position: state.options.strategy,');
  FPack.Add('        adaptive: adaptive,');
  FPack.Add('        roundOffsets: roundOffsets');
  FPack.Add('      })));');
  FPack.Add('    }');
  FPack.Add('');
  FPack.Add('    if (state.modifiersData.arrow != null) {');
  FPack.Add('      state.styles.arrow = Object.assign({}, state.styles.arrow, mapToStyles(Object.assign({}, commonStyles, {');
  FPack.Add('        offsets: state.modifiersData.arrow,');
  FPack.Add('        position: ''absolute'',');
  FPack.Add('        adaptive: false,');
  FPack.Add('        roundOffsets: roundOffsets');
  FPack.Add('      })));');
  FPack.Add('    }');
  FPack.Add('');
  FPack.Add('    state.attributes.popper = Object.assign({}, state.attributes.popper, {');
  FPack.Add('      ''data-popper-placement'': state.placement');
  FPack.Add('    });');
  FPack.Add('  } // eslint-disable-next-line import/no-unused-modules');
  FPack.Add('');
  FPack.Add('');
  FPack.Add('  var computeStyles$1 = {');
  FPack.Add('    name: ''computeStyles'',');
  FPack.Add('    enabled: true,');
  FPack.Add('    phase: ''beforeWrite'',');
  FPack.Add('    fn: computeStyles,');
  FPack.Add('    data: {}');
  FPack.Add('  };');
  FPack.Add('');
  FPack.Add('  // and applies them to the HTMLElements such as popper and arrow');
  FPack.Add('');
  FPack.Add('  function applyStyles(_ref) {');
  FPack.Add('    var state = _ref.state;');
  FPack.Add('    Object.keys(state.elements).forEach(function (name) {');
  FPack.Add('      var style = state.styles[name] || {};');
  FPack.Add('      var attributes = state.attributes[name] || {};');
  FPack.Add('      var element = state.elements[name]; // arrow is optional + virtual elements');
  FPack.Add('');
  FPack.Add('      if (!isHTMLElement(element) || !getNodeName(element)) {');
  FPack.Add('        return;');
  FPack.Add('      } // Flow doesn''t support to extend this property, but it''s the most');
  FPack.Add('      // effective way to apply styles to an HTMLElement');
  FPack.Add('      // $FlowFixMe[cannot-write]');
  FPack.Add('');
  FPack.Add('');
  FPack.Add('      Object.assign(element.style, style);');
  FPack.Add('      Object.keys(attributes).forEach(function (name) {');
  FPack.Add('        var value = attributes[name];');
  FPack.Add('');
  FPack.Add('        if (value === false) {');
  FPack.Add('          element.removeAttribute(name);');
  FPack.Add('        } else {');
  FPack.Add('          element.setAttribute(name, value === true ? '''' : value);');
  FPack.Add('        }');
  FPack.Add('      });');
  FPack.Add('    });');
  FPack.Add('  }');
  FPack.Add('');
  FPack.Add('  function effect$1(_ref2) {');
  FPack.Add('    var state = _ref2.state;');
  FPack.Add('    var initialStyles = {');
  FPack.Add('      popper: {');
  FPack.Add('        position: state.options.strategy,');
  FPack.Add('        left: ''0'',');
  FPack.Add('        top: ''0'',');
  FPack.Add('        margin: ''0''');
  FPack.Add('      },');
  FPack.Add('      arrow: {');
  FPack.Add('        position: ''absolute''');
  FPack.Add('      },');
  FPack.Add('      reference: {}');
  FPack.Add('    };');
  FPack.Add('    Object.assign(state.elements.popper.style, initialStyles.popper);');
  FPack.Add('    state.styles = initialStyles;');
  FPack.Add('');
  FPack.Add('    if (state.elements.arrow) {');
  FPack.Add('      Object.assign(state.elements.arrow.style, initialStyles.arrow);');
  FPack.Add('    }');
  FPack.Add('');
  FPack.Add('    return function () {');
  FPack.Add('      Object.keys(state.elements).forEach(function (name) {');
  FPack.Add('        var element = state.elements[name];');
  FPack.Add('        var attributes = state.attributes[name] || {};');
  FPack.Add('        var styleProperties = Object.keys(state.styles.hasOwnProperty(name) ? state.styles[name] : initialStyles[name]); // Set all values to an empty string to unset them');
  FPack.Add('');
  FPack.Add('        var style = styleProperties.reduce(function (style, property) {');
  FPack.Add('          style[property] = '''';');
  FPack.Add('          return style;');
  FPack.Add('        }, {}); // arrow is optional + virtual elements');
  FPack.Add('');
  FPack.Add('        if (!isHTMLElement(element) || !getNodeName(element)) {');
  FPack.Add('          return;');
  FPack.Add('        }');
  FPack.Add('');
  FPack.Add('        Object.assign(element.style, style);');
  FPack.Add('        Object.keys(attributes).forEach(function (attribute) {');
  FPack.Add('          element.removeAttribute(attribute);');
  FPack.Add('        });');
  FPack.Add('      });');
  FPack.Add('    };');
  FPack.Add('  } // eslint-disable-next-line import/no-unused-modules');
  FPack.Add('');
  FPack.Add('');
  FPack.Add('  var applyStyles$1 = {');
  FPack.Add('    name: ''applyStyles'',');
  FPack.Add('    enabled: true,');
  FPack.Add('    phase: ''write'',');
  FPack.Add('    fn: applyStyles,');
  FPack.Add('    effect: effect$1,');
  FPack.Add('    requires: [''computeStyles'']');
  FPack.Add('  };');
  FPack.Add('');
  FPack.Add('  function distanceAndSkiddingToXY(placement, rects, offset) {');
  FPack.Add('    var basePlacement = getBasePlacement(placement);');
  FPack.Add('    var invertDistance = [left, top].indexOf(basePlacement) >= 0 ? -1 : 1;');
  FPack.Add('');
  FPack.Add('    var _ref = typeof offset === ''function'' ? offset(Object.assign({}, rects, {');
  FPack.Add('      placement: placement');
  FPack.Add('    })) : offset,');
  FPack.Add('        skidding = _ref[0],');
  FPack.Add('        distance = _ref[1];');
  FPack.Add('');
  FPack.Add('    skidding = skidding || 0;');
  FPack.Add('    distance = (distance || 0) * invertDistance;');
  FPack.Add('    return [left, right].indexOf(basePlacement) >= 0 ? {');
  FPack.Add('      x: distance,');
  FPack.Add('      y: skidding');
  FPack.Add('    } : {');
  FPack.Add('      x: skidding,');
  FPack.Add('      y: distance');
  FPack.Add('    };');
  FPack.Add('  }');
  FPack.Add('');
  FPack.Add('  function offset(_ref2) {');
  FPack.Add('    var state = _ref2.state,');
  FPack.Add('        options = _ref2.options,');
  FPack.Add('        name = _ref2.name;');
  FPack.Add('    var _options$offset = options.offset,');
  FPack.Add('        offset = _options$offset === void 0 ? [0, 0] : _options$offset;');
  FPack.Add('    var data = placements.reduce(function (acc, placement) {');
  FPack.Add('      acc[placement] = distanceAndSkiddingToXY(placement, state.rects, offset);');
  FPack.Add('      return acc;');
  FPack.Add('    }, {});');
  FPack.Add('    var _data$state$placement = data[state.placement],');
  FPack.Add('        x = _data$state$placement.x,');
  FPack.Add('        y = _data$state$placement.y;');
  FPack.Add('');
  FPack.Add('    if (state.modifiersData.popperOffsets != null) {');
  FPack.Add('      state.modifiersData.popperOffsets.x += x;');
  FPack.Add('      state.modifiersData.popperOffsets.y += y;');
  FPack.Add('    }');
  FPack.Add('');
  FPack.Add('    state.modifiersData[name] = data;');
  FPack.Add('  } // eslint-disable-next-line import/no-unused-modules');
  FPack.Add('');
  FPack.Add('');
  FPack.Add('  var offset$1 = {');
  FPack.Add('    name: ''offset'',');
  FPack.Add('    enabled: true,');
  FPack.Add('    phase: ''main'',');
  FPack.Add('    requires: [''popperOffsets''],');
  FPack.Add('    fn: offset');
  FPack.Add('  };');
  FPack.Add('');
  FPack.Add('  var hash$1 = {');
  FPack.Add('    left: ''right'',');
  FPack.Add('    right: ''left'',');
  FPack.Add('    bottom: ''top'',');
  FPack.Add('    top: ''bottom''');
  FPack.Add('  };');
  FPack.Add('  function getOppositePlacement(placement) {');
  FPack.Add('    return placement.replace(/left|right|bottom|top/g, function (matched) {');
  FPack.Add('      return hash$1[matched];');
  FPack.Add('    });');
  FPack.Add('  }');
  FPack.Add('');
  FPack.Add('  var hash = {');
  FPack.Add('    start: ''end'',');
  FPack.Add('    end: ''start''');
  FPack.Add('  };');
  FPack.Add('  function getOppositeVariationPlacement(placement) {');
  FPack.Add('    return placement.replace(/start|end/g, function (matched) {');
  FPack.Add('      return hash[matched];');
  FPack.Add('    });');
  FPack.Add('  }');
  FPack.Add('');
  FPack.Add('  function computeAutoPlacement(state, options) {');
  FPack.Add('    if (options === void 0) {');
  FPack.Add('      options = {};');
  FPack.Add('    }');
  FPack.Add('');
  FPack.Add('    var _options = options,');
  FPack.Add('        placement = _options.placement,');
  FPack.Add('        boundary = _options.boundary,');
  FPack.Add('        rootBoundary = _options.rootBoundary,');
  FPack.Add('        padding = _options.padding,');
  FPack.Add('        flipVariations = _options.flipVariations,');
  FPack.Add('        _options$allowedAutoP = _options.allowedAutoPlacements,');
  FPack.Add('        allowedAutoPlacements = _options$allowedAutoP === void 0 ? placements : _options$allowedAutoP;');
  FPack.Add('    var variation = getVariation(placement);');
  FPack.Add('    var placements$1 = variation ? flipVariations ? variationPlacements : variationPlacements.filter(function (placement) {');
  FPack.Add('      return getVariation(placement) === variation;');
  FPack.Add('    }) : basePlacements;');
  FPack.Add('    var allowedPlacements = placements$1.filter(function (placement) {');
  FPack.Add('      return allowedAutoPlacements.indexOf(placement) >= 0;');
  FPack.Add('    });');
  FPack.Add('');
  FPack.Add('    if (allowedPlacements.length === 0) {');
  FPack.Add('      allowedPlacements = placements$1;');
  FPack.Add('    } // $FlowFixMe[incompatible-type]: Flow seems to have problems with two array unions...');
  FPack.Add('');
  FPack.Add('');
  FPack.Add('    var overflows = allowedPlacements.reduce(function (acc, placement) {');
  FPack.Add('      acc[placement] = detectOverflow(state, {');
  FPack.Add('        placement: placement,');
  FPack.Add('        boundary: boundary,');
  FPack.Add('        rootBoundary: rootBoundary,');
  FPack.Add('        padding: padding');
  FPack.Add('      })[getBasePlacement(placement)];');
  FPack.Add('      return acc;');
  FPack.Add('    }, {});');
  FPack.Add('    return Object.keys(overflows).sort(function (a, b) {');
  FPack.Add('      return overflows[a] - overflows[b];');
  FPack.Add('    });');
  FPack.Add('  }');
  FPack.Add('');
  FPack.Add('  function getExpandedFallbackPlacements(placement) {');
  FPack.Add('    if (getBasePlacement(placement) === auto) {');
  FPack.Add('      return [];');
  FPack.Add('    }');
  FPack.Add('');
  FPack.Add('    var oppositePlacement = getOppositePlacement(placement);');
  FPack.Add('    return [getOppositeVariationPlacement(placement), oppositePlacement, getOppositeVariationPlacement(oppositePlacement)];');
  FPack.Add('  }');
  FPack.Add('');
  FPack.Add('  function flip(_ref) {');
  FPack.Add('    var state = _ref.state,');
  FPack.Add('        options = _ref.options,');
  FPack.Add('        name = _ref.name;');
  FPack.Add('');
  FPack.Add('    if (state.modifiersData[name]._skip) {');
  FPack.Add('      return;');
  FPack.Add('    }');
  FPack.Add('');
  FPack.Add('    var _options$mainAxis = options.mainAxis,');
  FPack.Add('        checkMainAxis = _options$mainAxis === void 0 ? true : _options$mainAxis,');
  FPack.Add('        _options$altAxis = options.altAxis,');
  FPack.Add('        checkAltAxis = _options$altAxis === void 0 ? true : _options$altAxis,');
  FPack.Add('        specifiedFallbackPlacements = options.fallbackPlacements,');
  FPack.Add('        padding = options.padding,');
  FPack.Add('        boundary = options.boundary,');
  FPack.Add('        rootBoundary = options.rootBoundary,');
end;

procedure TPopperJS.PopperJS_5;
begin
  FPack.Add('        altBoundary = options.altBoundary,');
  FPack.Add('        _options$flipVariatio = options.flipVariations,');
  FPack.Add('        flipVariations = _options$flipVariatio === void 0 ? true : _options$flipVariatio,');
  FPack.Add('        allowedAutoPlacements = options.allowedAutoPlacements;');
  FPack.Add('    var preferredPlacement = state.options.placement;');
  FPack.Add('    var basePlacement = getBasePlacement(preferredPlacement);');
  FPack.Add('    var isBasePlacement = basePlacement === preferredPlacement;');
  FPack.Add('    var fallbackPlacements = specifiedFallbackPlacements || (isBasePlacement || !flipVariations ? [getOppositePlacement(preferredPlacement)] : getExpandedFallbackPlacements(preferredPlacement));');
  FPack.Add('    var placements = [preferredPlacement].concat(fallbackPlacements).reduce(function (acc, placement) {');
  FPack.Add('      return acc.concat(getBasePlacement(placement) === auto ? computeAutoPlacement(state, {');
  FPack.Add('        placement: placement,');
  FPack.Add('        boundary: boundary,');
  FPack.Add('        rootBoundary: rootBoundary,');
  FPack.Add('        padding: padding,');
  FPack.Add('        flipVariations: flipVariations,');
  FPack.Add('        allowedAutoPlacements: allowedAutoPlacements');
  FPack.Add('      }) : placement);');
  FPack.Add('    }, []);');
  FPack.Add('    var referenceRect = state.rects.reference;');
  FPack.Add('    var popperRect = state.rects.popper;');
  FPack.Add('    var checksMap = new Map();');
  FPack.Add('    var makeFallbackChecks = true;');
  FPack.Add('    var firstFittingPlacement = placements[0];');
  FPack.Add('');
  FPack.Add('    for (var i = 0; i < placements.length; i++) {');
  FPack.Add('      var placement = placements[i];');
  FPack.Add('');
  FPack.Add('      var _basePlacement = getBasePlacement(placement);');
  FPack.Add('');
  FPack.Add('      var isStartVariation = getVariation(placement) === start;');
  FPack.Add('      var isVertical = [top, bottom].indexOf(_basePlacement) >= 0;');
  FPack.Add('      var len = isVertical ? ''width'' : ''height'';');
  FPack.Add('      var overflow = detectOverflow(state, {');
  FPack.Add('        placement: placement,');
  FPack.Add('        boundary: boundary,');
  FPack.Add('        rootBoundary: rootBoundary,');
  FPack.Add('        altBoundary: altBoundary,');
  FPack.Add('        padding: padding');
  FPack.Add('      });');
  FPack.Add('      var mainVariationSide = isVertical ? isStartVariation ? right : left : isStartVariation ? bottom : top;');
  FPack.Add('');
  FPack.Add('      if (referenceRect[len] > popperRect[len]) {');
  FPack.Add('        mainVariationSide = getOppositePlacement(mainVariationSide);');
  FPack.Add('      }');
  FPack.Add('');
  FPack.Add('      var altVariationSide = getOppositePlacement(mainVariationSide);');
  FPack.Add('      var checks = [];');
  FPack.Add('');
  FPack.Add('      if (checkMainAxis) {');
  FPack.Add('        checks.push(overflow[_basePlacement] <= 0);');
  FPack.Add('      }');
  FPack.Add('');
  FPack.Add('      if (checkAltAxis) {');
  FPack.Add('        checks.push(overflow[mainVariationSide] <= 0, overflow[altVariationSide] <= 0);');
  FPack.Add('      }');
  FPack.Add('');
  FPack.Add('      if (checks.every(function (check) {');
  FPack.Add('        return check;');
  FPack.Add('      })) {');
  FPack.Add('        firstFittingPlacement = placement;');
  FPack.Add('        makeFallbackChecks = false;');
  FPack.Add('        break;');
  FPack.Add('      }');
  FPack.Add('');
  FPack.Add('      checksMap.set(placement, checks);');
  FPack.Add('    }');
  FPack.Add('');
  FPack.Add('    if (makeFallbackChecks) {');
  FPack.Add('      // `2` may be desired in some cases – research later');
  FPack.Add('      var numberOfChecks = flipVariations ? 3 : 1;');
  FPack.Add('');
  FPack.Add('      var _loop = function _loop(_i) {');
  FPack.Add('        var fittingPlacement = placements.find(function (placement) {');
  FPack.Add('          var checks = checksMap.get(placement);');
  FPack.Add('');
  FPack.Add('          if (checks) {');
  FPack.Add('            return checks.slice(0, _i).every(function (check) {');
  FPack.Add('              return check;');
  FPack.Add('            });');
  FPack.Add('          }');
  FPack.Add('        });');
  FPack.Add('');
  FPack.Add('        if (fittingPlacement) {');
  FPack.Add('          firstFittingPlacement = fittingPlacement;');
  FPack.Add('          return "break";');
  FPack.Add('        }');
  FPack.Add('      };');
  FPack.Add('');
  FPack.Add('      for (var _i = numberOfChecks; _i > 0; _i--) {');
  FPack.Add('        var _ret = _loop(_i);');
  FPack.Add('');
  FPack.Add('        if (_ret === "break") break;');
  FPack.Add('      }');
  FPack.Add('    }');
  FPack.Add('');
  FPack.Add('    if (state.placement !== firstFittingPlacement) {');
  FPack.Add('      state.modifiersData[name]._skip = true;');
  FPack.Add('      state.placement = firstFittingPlacement;');
  FPack.Add('      state.reset = true;');
  FPack.Add('    }');
  FPack.Add('  } // eslint-disable-next-line import/no-unused-modules');
  FPack.Add('');
  FPack.Add('');
  FPack.Add('  var flip$1 = {');
  FPack.Add('    name: ''flip'',');
  FPack.Add('    enabled: true,');
  FPack.Add('    phase: ''main'',');
  FPack.Add('    fn: flip,');
  FPack.Add('    requiresIfExists: [''offset''],');
  FPack.Add('    data: {');
  FPack.Add('      _skip: false');
  FPack.Add('    }');
  FPack.Add('  };');
  FPack.Add('');
  FPack.Add('  function getAltAxis(axis) {');
  FPack.Add('    return axis === ''x'' ? ''y'' : ''x'';');
  FPack.Add('  }');
  FPack.Add('');
  FPack.Add('  function within(min$1, value, max$1) {');
  FPack.Add('    return max(min$1, min(value, max$1));');
  FPack.Add('  }');
  FPack.Add('  function withinMaxClamp(min, value, max) {');
  FPack.Add('    var v = within(min, value, max);');
  FPack.Add('    return v > max ? max : v;');
  FPack.Add('  }');
  FPack.Add('');
  FPack.Add('  function preventOverflow(_ref) {');
  FPack.Add('    var state = _ref.state,');
  FPack.Add('        options = _ref.options,');
  FPack.Add('        name = _ref.name;');
  FPack.Add('    var _options$mainAxis = options.mainAxis,');
  FPack.Add('        checkMainAxis = _options$mainAxis === void 0 ? true : _options$mainAxis,');
  FPack.Add('        _options$altAxis = options.altAxis,');
  FPack.Add('        checkAltAxis = _options$altAxis === void 0 ? false : _options$altAxis,');
  FPack.Add('        boundary = options.boundary,');
  FPack.Add('        rootBoundary = options.rootBoundary,');
  FPack.Add('        altBoundary = options.altBoundary,');
  FPack.Add('        padding = options.padding,');
  FPack.Add('        _options$tether = options.tether,');
  FPack.Add('        tether = _options$tether === void 0 ? true : _options$tether,');
  FPack.Add('        _options$tetherOffset = options.tetherOffset,');
  FPack.Add('        tetherOffset = _options$tetherOffset === void 0 ? 0 : _options$tetherOffset;');
  FPack.Add('    var overflow = detectOverflow(state, {');
  FPack.Add('      boundary: boundary,');
  FPack.Add('      rootBoundary: rootBoundary,');
  FPack.Add('      padding: padding,');
  FPack.Add('      altBoundary: altBoundary');
  FPack.Add('    });');
  FPack.Add('    var basePlacement = getBasePlacement(state.placement);');
  FPack.Add('    var variation = getVariation(state.placement);');
  FPack.Add('    var isBasePlacement = !variation;');
  FPack.Add('    var mainAxis = getMainAxisFromPlacement(basePlacement);');
  FPack.Add('    var altAxis = getAltAxis(mainAxis);');
  FPack.Add('    var popperOffsets = state.modifiersData.popperOffsets;');
  FPack.Add('    var referenceRect = state.rects.reference;');
  FPack.Add('    var popperRect = state.rects.popper;');
  FPack.Add('    var tetherOffsetValue = typeof tetherOffset === ''function'' ? tetherOffset(Object.assign({}, state.rects, {');
  FPack.Add('      placement: state.placement');
  FPack.Add('    })) : tetherOffset;');
  FPack.Add('    var normalizedTetherOffsetValue = typeof tetherOffsetValue === ''number'' ? {');
  FPack.Add('      mainAxis: tetherOffsetValue,');
  FPack.Add('      altAxis: tetherOffsetValue');
  FPack.Add('    } : Object.assign({');
  FPack.Add('      mainAxis: 0,');
  FPack.Add('      altAxis: 0');
  FPack.Add('    }, tetherOffsetValue);');
  FPack.Add('    var offsetModifierState = state.modifiersData.offset ? state.modifiersData.offset[state.placement] : null;');
  FPack.Add('    var data = {');
  FPack.Add('      x: 0,');
  FPack.Add('      y: 0');
  FPack.Add('    };');
  FPack.Add('');
  FPack.Add('    if (!popperOffsets) {');
  FPack.Add('      return;');
  FPack.Add('    }');
  FPack.Add('');
  FPack.Add('    if (checkMainAxis) {');
  FPack.Add('      var _offsetModifierState$;');
  FPack.Add('');
  FPack.Add('      var mainSide = mainAxis === ''y'' ? top : left;');
  FPack.Add('      var altSide = mainAxis === ''y'' ? bottom : right;');
  FPack.Add('      var len = mainAxis === ''y'' ? ''height'' : ''width'';');
  FPack.Add('      var offset = popperOffsets[mainAxis];');
  FPack.Add('      var min$1 = offset + overflow[mainSide];');
  FPack.Add('      var max$1 = offset - overflow[altSide];');
  FPack.Add('      var additive = tether ? -popperRect[len] / 2 : 0;');
  FPack.Add('      var minLen = variation === start ? referenceRect[len] : popperRect[len];');
  FPack.Add('      var maxLen = variation === start ? -popperRect[len] : -referenceRect[len]; // We need to include the arrow in the calculation so the arrow doesn''t go');
  FPack.Add('      // outside the reference bounds');
  FPack.Add('');
  FPack.Add('      var arrowElement = state.elements.arrow;');
  FPack.Add('      var arrowRect = tether && arrowElement ? getLayoutRect(arrowElement) : {');
  FPack.Add('        width: 0,');
  FPack.Add('        height: 0');
  FPack.Add('      };');
  FPack.Add('      var arrowPaddingObject = state.modifiersData[''arrow#persistent''] ? state.modifiersData[''arrow#persistent''].padding : getFreshSideObject();');
  FPack.Add('      var arrowPaddingMin = arrowPaddingObject[mainSide];');
  FPack.Add('      var arrowPaddingMax = arrowPaddingObject[altSide]; // If the reference length is smaller than the arrow length, we don''t want');
  FPack.Add('      // to include its full size in the calculation. If the reference is small');
  FPack.Add('      // and near the edge of a boundary, the popper can overflow even if the');
  FPack.Add('      // reference is not overflowing as well (e.g. virtual elements with no');
  FPack.Add('      // width or height)');
  FPack.Add('');
  FPack.Add('      var arrowLen = within(0, referenceRect[len], arrowRect[len]);');
  FPack.Add('      var minOffset = isBasePlacement ? referenceRect[len] / 2 - additive - arrowLen - arrowPaddingMin - normalizedTetherOffsetValue.mainAxis : minLen - arrowLen - arrowPaddingMin - normalizedTetherOffsetValue.mainAxis;');
  FPack.Add('      var maxOffset = isBasePlacement ? -referenceRect[len] / 2 + additive + arrowLen + arrowPaddingMax + normalizedTetherOffsetValue.mainAxis : maxLen + arrowLen + arrowPaddingMax + normalizedTetherOffsetValue.mainAxis;');
  FPack.Add('      var arrowOffsetParent = state.elements.arrow && getOffsetParent(state.elements.arrow);');
  FPack.Add('      var clientOffset = arrowOffsetParent ? mainAxis === ''y'' ? arrowOffsetParent.clientTop || 0 : arrowOffsetParent.clientLeft || 0 : 0;');
  FPack.Add('      var offsetModifierValue = (_offsetModifierState$ = offsetModifierState == null ? void 0 : offsetModifierState[mainAxis]) != null ? _offsetModifierState$ : 0;');
  FPack.Add('      var tetherMin = offset + minOffset - offsetModifierValue - clientOffset;');
  FPack.Add('      var tetherMax = offset + maxOffset - offsetModifierValue;');
  FPack.Add('      var preventedOffset = within(tether ? min(min$1, tetherMin) : min$1, offset, tether ? max(max$1, tetherMax) : max$1);');
  FPack.Add('      popperOffsets[mainAxis] = preventedOffset;');
  FPack.Add('      data[mainAxis] = preventedOffset - offset;');
  FPack.Add('    }');
  FPack.Add('');
  FPack.Add('    if (checkAltAxis) {');
  FPack.Add('      var _offsetModifierState$2;');
  FPack.Add('');
  FPack.Add('      var _mainSide = mainAxis === ''x'' ? top : left;');
  FPack.Add('');
  FPack.Add('      var _altSide = mainAxis === ''x'' ? bottom : right;');
  FPack.Add('');
  FPack.Add('      var _offset = popperOffsets[altAxis];');
  FPack.Add('');
  FPack.Add('      var _len = altAxis === ''y'' ? ''height'' : ''width'';');
  FPack.Add('');
  FPack.Add('      var _min = _offset + overflow[_mainSide];');
  FPack.Add('');
  FPack.Add('      var _max = _offset - overflow[_altSide];');
  FPack.Add('');
  FPack.Add('      var isOriginSide = [top, left].indexOf(basePlacement) !== -1;');
  FPack.Add('');
  FPack.Add('      var _offsetModifierValue = (_offsetModifierState$2 = offsetModifierState == null ? void 0 : offsetModifierState[altAxis]) != null ? _offsetModifierState$2 : 0;');
  FPack.Add('');
  FPack.Add('      var _tetherMin = isOriginSide ? _min : _offset - referenceRect[_len] - popperRect[_len] - _offsetModifierValue + normalizedTetherOffsetValue.altAxis;');
  FPack.Add('');
  FPack.Add('      var _tetherMax = isOriginSide ? _offset + referenceRect[_len] + popperRect[_len] - _offsetModifierValue - normalizedTetherOffsetValue.altAxis : _max;');
  FPack.Add('');
  FPack.Add('      var _preventedOffset = tether && isOriginSide ? withinMaxClamp(_tetherMin, _offset, _tetherMax) : within(tether ? _tetherMin : _min, _offset, tether ? _tetherMax : _max);');
  FPack.Add('');
  FPack.Add('      popperOffsets[altAxis] = _preventedOffset;');
  FPack.Add('      data[altAxis] = _preventedOffset - _offset;');
  FPack.Add('    }');
  FPack.Add('');
  FPack.Add('    state.modifiersData[name] = data;');
  FPack.Add('  } // eslint-disable-next-line import/no-unused-modules');
  FPack.Add('');
  FPack.Add('');
  FPack.Add('  var preventOverflow$1 = {');
  FPack.Add('    name: ''preventOverflow'',');
  FPack.Add('    enabled: true,');
  FPack.Add('    phase: ''main'',');
  FPack.Add('    fn: preventOverflow,');
  FPack.Add('    requiresIfExists: [''offset'']');
  FPack.Add('  };');
  FPack.Add('');
  FPack.Add('  var toPaddingObject = function toPaddingObject(padding, state) {');
  FPack.Add('    padding = typeof padding === ''function'' ? padding(Object.assign({}, state.rects, {');
  FPack.Add('      placement: state.placement');
  FPack.Add('    })) : padding;');
  FPack.Add('    return mergePaddingObject(typeof padding !== ''number'' ? padding : expandToHashMap(padding, basePlacements));');
  FPack.Add('  };');
  FPack.Add('');
  FPack.Add('  function arrow(_ref) {');
  FPack.Add('    var _state$modifiersData$;');
  FPack.Add('');
  FPack.Add('    var state = _ref.state,');
  FPack.Add('        name = _ref.name,');
  FPack.Add('        options = _ref.options;');
  FPack.Add('    var arrowElement = state.elements.arrow;');
  FPack.Add('    var popperOffsets = state.modifiersData.popperOffsets;');
  FPack.Add('    var basePlacement = getBasePlacement(state.placement);');
  FPack.Add('    var axis = getMainAxisFromPlacement(basePlacement);');
  FPack.Add('    var isVertical = [left, right].indexOf(basePlacement) >= 0;');
  FPack.Add('    var len = isVertical ? ''height'' : ''width'';');
  FPack.Add('');
  FPack.Add('    if (!arrowElement || !popperOffsets) {');
  FPack.Add('      return;');
  FPack.Add('    }');
  FPack.Add('');
  FPack.Add('    var paddingObject = toPaddingObject(options.padding, state);');
  FPack.Add('    var arrowRect = getLayoutRect(arrowElement);');
  FPack.Add('    var minProp = axis === ''y'' ? top : left;');
  FPack.Add('    var maxProp = axis === ''y'' ? bottom : right;');
  FPack.Add('    var endDiff = state.rects.reference[len] + state.rects.reference[axis] - popperOffsets[axis] - state.rects.popper[len];');
  FPack.Add('    var startDiff = popperOffsets[axis] - state.rects.reference[axis];');
  FPack.Add('    var arrowOffsetParent = getOffsetParent(arrowElement);');
  FPack.Add('    var clientSize = arrowOffsetParent ? axis === ''y'' ? arrowOffsetParent.clientHeight || 0 : arrowOffsetParent.clientWidth || 0 : 0;');
  FPack.Add('    var centerToReference = endDiff / 2 - startDiff / 2; // Make sure the arrow doesn''t overflow the popper if the center point is');
  FPack.Add('    // outside of the popper bounds');
  FPack.Add('');
  FPack.Add('    var min = paddingObject[minProp];');
  FPack.Add('    var max = clientSize - arrowRect[len] - paddingObject[maxProp];');
  FPack.Add('    var center = clientSize / 2 - arrowRect[len] / 2 + centerToReference;');
  FPack.Add('    var offset = within(min, center, max); // Prevents breaking syntax highlighting...');
  FPack.Add('');
  FPack.Add('    var axisProp = axis;');
  FPack.Add('    state.modifiersData[name] = (_state$modifiersData$ = {}, _state$modifiersData$[axisProp] = offset, _state$modifiersData$.centerOffset = offset - center, _state$modifiersData$);');
  FPack.Add('  }');
  FPack.Add('');
  FPack.Add('  function effect(_ref2) {');
  FPack.Add('    var state = _ref2.state,');
  FPack.Add('        options = _ref2.options;');
  FPack.Add('    var _options$element = options.element,');
  FPack.Add('        arrowElement = _options$element === void 0 ? ''[data-popper-arrow]'' : _options$element;');
  FPack.Add('');
  FPack.Add('    if (arrowElement == null) {');
  FPack.Add('      return;');
  FPack.Add('    } // CSS selector');
  FPack.Add('');
  FPack.Add('');
  FPack.Add('    if (typeof arrowElement === ''string'') {');
  FPack.Add('      arrowElement = state.elements.popper.querySelector(arrowElement);');
  FPack.Add('');
  FPack.Add('      if (!arrowElement) {');
  FPack.Add('        return;');
  FPack.Add('      }');
  FPack.Add('    }');
  FPack.Add('');
  FPack.Add('    if (!contains(state.elements.popper, arrowElement)) {');
  FPack.Add('      return;');
  FPack.Add('    }');
  FPack.Add('');
  FPack.Add('    state.elements.arrow = arrowElement;');
  FPack.Add('  } // eslint-disable-next-line import/no-unused-modules');
  FPack.Add('');
  FPack.Add('');
  FPack.Add('  var arrow$1 = {');
  FPack.Add('    name: ''arrow'',');
  FPack.Add('    enabled: true,');
  FPack.Add('    phase: ''main'',');
  FPack.Add('    fn: arrow,');
  FPack.Add('    effect: effect,');
  FPack.Add('    requires: [''popperOffsets''],');
  FPack.Add('    requiresIfExists: [''preventOverflow'']');
  FPack.Add('  };');
  FPack.Add('');
  FPack.Add('  function getSideOffsets(overflow, rect, preventedOffsets) {');
  FPack.Add('    if (preventedOffsets === void 0) {');
  FPack.Add('      preventedOffsets = {');
  FPack.Add('        x: 0,');
  FPack.Add('        y: 0');
  FPack.Add('      };');
  FPack.Add('    }');
  FPack.Add('');
  FPack.Add('    return {');
  FPack.Add('      top: overflow.top - rect.height - preventedOffsets.y,');
  FPack.Add('      right: overflow.right - rect.width + preventedOffsets.x,');
  FPack.Add('      bottom: overflow.bottom - rect.height + preventedOffsets.y,');
end;

procedure TPopperJS.PopperJS_6;
begin
  FPack.Add('      left: overflow.left - rect.width - preventedOffsets.x');
  FPack.Add('    };');
  FPack.Add('  }');
  FPack.Add('');
  FPack.Add('  function isAnySideFullyClipped(overflow) {');
  FPack.Add('    return [top, right, bottom, left].some(function (side) {');
  FPack.Add('      return overflow[side] >= 0;');
  FPack.Add('    });');
  FPack.Add('  }');
  FPack.Add('');
  FPack.Add('  function hide(_ref) {');
  FPack.Add('    var state = _ref.state,');
  FPack.Add('        name = _ref.name;');
  FPack.Add('    var referenceRect = state.rects.reference;');
  FPack.Add('    var popperRect = state.rects.popper;');
  FPack.Add('    var preventedOffsets = state.modifiersData.preventOverflow;');
  FPack.Add('    var referenceOverflow = detectOverflow(state, {');
  FPack.Add('      elementContext: ''reference''');
  FPack.Add('    });');
  FPack.Add('    var popperAltOverflow = detectOverflow(state, {');
  FPack.Add('      altBoundary: true');
  FPack.Add('    });');
  FPack.Add('    var referenceClippingOffsets = getSideOffsets(referenceOverflow, referenceRect);');
  FPack.Add('    var popperEscapeOffsets = getSideOffsets(popperAltOverflow, popperRect, preventedOffsets);');
  FPack.Add('    var isReferenceHidden = isAnySideFullyClipped(referenceClippingOffsets);');
  FPack.Add('    var hasPopperEscaped = isAnySideFullyClipped(popperEscapeOffsets);');
  FPack.Add('    state.modifiersData[name] = {');
  FPack.Add('      referenceClippingOffsets: referenceClippingOffsets,');
  FPack.Add('      popperEscapeOffsets: popperEscapeOffsets,');
  FPack.Add('      isReferenceHidden: isReferenceHidden,');
  FPack.Add('      hasPopperEscaped: hasPopperEscaped');
  FPack.Add('    };');
  FPack.Add('    state.attributes.popper = Object.assign({}, state.attributes.popper, {');
  FPack.Add('      ''data-popper-reference-hidden'': isReferenceHidden,');
  FPack.Add('      ''data-popper-escaped'': hasPopperEscaped');
  FPack.Add('    });');
  FPack.Add('  } // eslint-disable-next-line import/no-unused-modules');
  FPack.Add('');
  FPack.Add('');
  FPack.Add('  var hide$1 = {');
  FPack.Add('    name: ''hide'',');
  FPack.Add('    enabled: true,');
  FPack.Add('    phase: ''main'',');
  FPack.Add('    requiresIfExists: [''preventOverflow''],');
  FPack.Add('    fn: hide');
  FPack.Add('  };');
  FPack.Add('');
  FPack.Add('  var defaultModifiers$1 = [eventListeners, popperOffsets$1, computeStyles$1, applyStyles$1];');
  FPack.Add('  var createPopper$1 = /*#__PURE__*/popperGenerator({');
  FPack.Add('    defaultModifiers: defaultModifiers$1');
  FPack.Add('  }); // eslint-disable-next-line import/no-unused-modules');
  FPack.Add('');
  FPack.Add('  var defaultModifiers = [eventListeners, popperOffsets$1, computeStyles$1, applyStyles$1, offset$1, flip$1, preventOverflow$1, arrow$1, hide$1];');
  FPack.Add('  var createPopper = /*#__PURE__*/popperGenerator({');
  FPack.Add('    defaultModifiers: defaultModifiers');
  FPack.Add('  }); // eslint-disable-next-line import/no-unused-modules');
  FPack.Add('');
  FPack.Add('  exports.applyStyles = applyStyles$1;');
  FPack.Add('  exports.arrow = arrow$1;');
  FPack.Add('  exports.computeStyles = computeStyles$1;');
  FPack.Add('  exports.createPopper = createPopper;');
  FPack.Add('  exports.createPopperLite = createPopper$1;');
  FPack.Add('  exports.defaultModifiers = defaultModifiers;');
  FPack.Add('  exports.detectOverflow = detectOverflow;');
  FPack.Add('  exports.eventListeners = eventListeners;');
  FPack.Add('  exports.flip = flip$1;');
  FPack.Add('  exports.hide = hide$1;');
  FPack.Add('  exports.offset = offset$1;');
  FPack.Add('  exports.popperGenerator = popperGenerator;');
  FPack.Add('  exports.popperOffsets = popperOffsets$1;');
  FPack.Add('  exports.preventOverflow = preventOverflow$1;');
  FPack.Add('');
  FPack.Add('  Object.defineProperty(exports, ''__esModule'', { value: true });');
  FPack.Add('');
  FPack.Add('})));');
  FPack.Add('//# sourceMappingURL=popper.js.map');
  FPack.Add('');
  FPack.Add('</script>'+#13);
end;
function TPopperJS.PackJS: String;
begin
  if FCDN then
    Result := '<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/2.11.8/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script>'
  else
  begin
    PopperJS_1;
    PopperJS_2;
    PopperJS_3;
    PopperJS_4;
    PopperJS_5;
    PopperJS_6;
    Result := FPack.Text;
  end;
end;

end.
